### ISSUE TITLE
"BrokenPipeError: [Errno 32] Broken pipe" with driver version 1.1.0

### ISSUE THREAD

**Issue by NikitaAtPlanOne** [neo4j/neo4j-python-driver#131]
Hi,

I just updated to driver version **1.1.0**. 
In my flask application I request a driver once at startup like this:

`driver = neo4j.GraphDatabase.driver(NEO4J_URL, auth=neo4j.basic_auth(NEO4J_USERNAME, NEO4J_PASSWORD))`

I then get sessions from the driver and run queries. However, when the server is idle for a longer period, I get the following exception:

> Traceback (most recent call last):
> File "connector.py", line 64, in query
>   raw_result = session.run(query, args)
> File ".virtualenvs/env/lib/python3.5/site-packages/neo4j/v1/bolt.py", line 145, in run
>     self.connection.send()
> File ".virtualenvs/env/lib/python3.5/site-packages/neo4j/bolt/connection.py", line 347, in send
>      self.channel.send()
> File ".virtualenvs/env/lib/python3.5/site-packages/neo4j/bolt/connection.py", line 192, in send
>       self.socket.sendall(data)
> File ".virtualenvs/env/lib/python3.5/site-packages/gevent/_ssl3.py", line 378, in sendall
>       return socket.sendall(self, data, flags)
> File ".virtualenvs/env/lib/python3.5/site-packages/gevent/_socket3.py", line 395, in sendall
>        data_sent += self.send(data_memory[data_sent:], flags)
> File ".virtualenvs/env/lib/python3.5/site-packages/gevent/_ssl3.py", line 341, in send
>       return self._sslobj.write(data)
> BrokenPipeError: [Errno 32] Broken pipe

Right before the exception occurs, the following messages appear in the log file:

> C: RUN (' ... ')
> C: PULL_ALL ()
> ~~ [CONNECT] (SERVER, PORT)
> ~~ [SECURE] SERVER

After the first exception, a further exception is dumped with the following messages printed in between:

> C: [HANDSHAKE] 0x6060B017 [1, 0, 0, 0]
> ...
> S: [HANDSHAKE] 1
> ...
> C: INIT ('neo4j-python/1.1.0', {'principal': '...', 'scheme': 'basic', 'credentials': '...'})
> ...
> BrokenPipeError: [Errno 32] Broken pipe

With driver version **1.1.0b1**, there was a delay after a longer idle period but then it worked as expected.
Here is an excerpt of the log with driver version **1.1.0b1** of such a situation:

> C: RUN (' ... ')
> C: PULL_ALL ()
> __Exception without Broken pipe__
> ...
> ~~ [CONNECT] (SERVER, PORT)
> ~~ [SECURE] SERVER
> C: [HANDSHAKE] 0x6060B017 [1, 0, 0, 0]
> S: [HANDSHAKE] 1
> C: INIT ('neo4j-python/1.1.0', {'principal': '...', 'scheme': 'basic', 'credentials': '...'})
> S: SUCCESS {}
> C: RUN (' ... ')
> ...

Is there a misunderstanding on my side of how to use the driver in a long running server application? 

Can I check if the driver still has a valid connection, e.g., by calling `session.closed()`?

**Comment by technige** [comment]
This is likely to be cause by a piece of intermediary network infrastructure timing out connections. Version 1.2 of the driver introduced support for TCP keep alive although the frequency of this heartbeat needs to be set at operating system level.

Can you clarify your network topology and whether or not you are using something like a load balancer?

**Comment by technige** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Connection Management [2 + max 4]](https://trello.com/c/DFeRQfab/50-connection-management-2-max-4)

**Comment by technige** [comment]
Closing due to inactivity. Please reopen if more information surfaces.

**Comment by jdbalistreri** [comment]
Hi Nigel,

I'm experiencing a similar issue to what Nikita described. I tried following your advice about setting a tcp keepalive at the os level and was having trouble finding the right information. 

Right now, I am running my application on AWS Elastic Beanstalk and communicating with a Neo4j cluster hosted by [Graphene](https://www.graphenedb.com/). I've reached out to Graphene and they have verified their keep alive settings are correctly configured - I have a feeling the misconfiguration is on our side.

Are you familiar enough with AWS architecture/implementation to provide guidance on where I might be running into trouble? If not, what is the best way for me to find my keep alive settings and diagnose which part of the architecture might be timing out connections?

Thank you,
Joe

**Comment by b-d055** [comment]
Nigel, I too am getting this same error. I am also getting some intermittent Service Unavailable errors. My flask app is running on a Heroku dyno  backed by GrapheneDB. We are using Neo4j 3.2.5 and neo4j-driver 1.4.0. I have been troubleshooting this for a week and can't seem to figure out why this is happening.

**Comment by zhenlineo** [comment]
@jdbalistreri @b-d055 Following the original explanation by Nigel, if the problem was caused by aws(or Azure or router etc.) timing out connections, you could try out the [1.5.0-rc](https://github.com/neo4j/neo4j-python-driver/releases/tag/1.5.0rc1) releases and config `max_connection_lifetime` to a smaller number than your aws connection timeout. (Note aws might use a **idle** connection timeout, for that cause, you might want to set aws idle to its maximum allowed value and then give that value to driver `max_connection_lifetime`.)

**Comment by b-d055** [comment]
@zhenlineo thank you for this, going forward I will consider. For now, I have written an error handler to deal with these connection issues. I found that simply making a new driver connection, when Service Unavailable or Broken Pipe is raised, was enough to fix it.
