### ISSUE TITLE
ValueError: '**/*.pyx'  while installing neo4j-driver-1.1.1

### ISSUE THREAD

**Issue by papachoco** [neo4j/neo4j-python-driver#138]
Hello,

While trying to upgrade neo4j-driver-1.1.1, using pip and easy-install I ran into the exception below

    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/jd/g7fjfbn57695542zy0j_84b40000gn/T/pip-build-1VfPje/neo4j-driver/setup.py", line 41, in <module>
        ext_modules = cythonize([Extension("*", ["**/*.pyx"])])
      File "/Users/csanchez/VirtualEnvs/nti.dataserver/lib/python2.7/site-packages/Cython-0.25.2-py2.7-macosx-10.12-x86_64.egg/Cython/Build/Dependencies.py", line 818, in cythonize
        aliases=aliases)
      File "/Users/csanchez/VirtualEnvs/nti.dataserver/lib/python2.7/site-packages/Cython-0.25.2-py2.7-macosx-10.12-x86_64.egg/Cython/Build/Dependencies.py", line 704, in create_extension_list
        for file in nonempty(sorted(extended_iglob(filepattern)), "'%s' doesn't match any files" % filepattern):
      File "/Users/csanchez/VirtualEnvs/nti.dataserver/lib/python2.7/site-packages/Cython-0.25.2-py2.7-macosx-10.12-x86_64.egg/Cython/Build/Dependencies.py", line 108, in nonempty
        raise ValueError(error_msg)
    ValueError: '**/*.pyx' doesn't match any files

Thanks 

Carlos

**Comment by technige** [comment]
Hi. Apologies for this problem, I managed to break the release process earlier today! Please try again to pick up 1.1.2.
