### ISSUE TITLE
ServiceUnavailable: Failed to read from closed connection after wait

### ISSUE THREAD

**Issue by john-bodley** [neo4j/neo4j-python-driver#143]
What causes Neo4j to close a connection? The following code,

```python
from neo4j.util import Watcher
from neo4j.v1 import GraphDatabase 
from time import sleep

Watcher("neo4j.bolt").watch()


def foo(driver):
    with driver.session() as session:
        results = session.run('MATCH (n) RETURN n LIMIT 10')
        for record in results:
            print record

driver = GraphDatabase.driver('bolt://localhost:7687')
foo(driver)
sleep(60)
foo(driver)
```
throws a `ServiceUnavailable` exception after the sleep, 
```
>>> foo(driver)
2017-04-19 14:25:01,197  C: RUN (u'MATCH (n) RETURN n LIMIT 10', {})
2017-04-19 14:25:01,198  C: PULL_ALL ()
2017-04-19 14:25:01,199  ~~ [CLOSE]
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "<stdin>", line 5, in foo
  File "/usr/local/lib/python2.7/dist-packages/neo4j/v1/api.py", line 229, in __exit__
    self.close()
  File "/usr/local/lib/python2.7/dist-packages/neo4j/v1/api.py", line 261, in close
    self._disconnect(sync=True)
  File "/usr/local/lib/python2.7/dist-packages/neo4j/v1/api.py", line 244, in _disconnect
    self._connection.sync()
  File "/usr/local/lib/python2.7/dist-packages/neo4j/bolt/connection.py", line 325, in sync
    detail_delta, summary_delta = self.fetch()
  File "/usr/local/lib/python2.7/dist-packages/neo4j/bolt/connection.py", line 249, in fetch
    raise self.Error("Failed to read from closed connection {!r}".format(self.server.address))
neo4j.exceptions.ServiceUnavailable: Failed to read from closed connection Address(host='127.0.0.1', port= 7687)
```

Note however if I execute `foo(driver)` after the exception is thrown it reconnects and the connection re-inits and the run statement is successful.

The only remedy I know is to redefine the `GraphDatabase.driver` prior to calling `foo(...)` for the second time, though I'm unsure why this is necessary. As far as I can tell Bolt does't have a specified timeout. 

Note I'm using `neo4j-driver` v1.2.0 with Python 2.7, and Neo4j v3.1.0.

**Comment by john-bodley** [comment]
Note I think the exception is somewhat of a misnomer as [this](https://github.com/neo4j/neo4j-python-driver/blob/1.2/neo4j/bolt/connection.py#L290) defunct exception is first thrown which I believe is caught (and consumed) [here](https://github.com/neo4j/neo4j-python-driver/blob/1.2/neo4j/v1/api.py#L258).

**Comment by johnbodley** [comment]
@technige do you know what the issue may be? I've tried debugging this but I'm somewhat at a loss at to what the issue is.

**Comment by john-bodley** [comment]
This turned out to be an issue with HAProxy rather than neo4j-driver.

**Comment by ghost** [comment]
@john-bodley could you detail how you fixed the HAProxy issue? I've been running into almost the exact issue using nginx+uwsgi and have been very confused as to what the best fix might be. Thanks!

**Comment by john-bodley** [comment]
@Shangyan-Li our setup is somewhat complicated, but for Bolt our configuration is something of the form, 
```
mode tcp
timeout connect 60s
timeout client 8h
timeout server 8h
```

**Comment by ghost** [comment]
Are you using HAProxy for a Neo4j cluster, or for the server on which the neo4j python driver is running? 


I'm still not quite sure what is causing the closed connection error – I'm using nginx as reverse proxy together with uwsgi (with a master process and a few sub-processes). I added some error handling code to restart a session (with the drawback that sometimes it takes a while until a session successfully returns something)
```    
def read_transaction_handler(self, fn, *args):
        while True:
            try:
                with self._driver.session() as session:
                    return session.read_transaction(fn, *args)
            except (BrokenPipeError, ServiceUnavailable, ConnectionResetError) as e:
                logging.warning('{}\nRead Transaction ERROR \n{}'.format('*' * 60, e))
```

Here's the relevant traceback I had (using driver ver 1.5): 

```
  File "/home/ubuntu/.virtualenvs/orca/lib/python3.5/site-packages/neo4j/v1/api.py", line 488, in read_transaction
    return self._run_transaction(READ_ACCESS, unit_of_work, *args, **kwargs)
  File "/home/ubuntu/.virtualenvs/orca/lib/python3.5/site-packages/neo4j/v1/api.py", line 485, in _run_transaction
    raise last_error
  File "/home/ubuntu/.virtualenvs/orca/lib/python3.5/site-packages/neo4j/v1/api.py", line 473, in _run_transaction
    return unit_of_work(tx, *args, **kwargs)
  File "/home/ubuntu/.virtualenvs/orca/lib/python3.5/site-packages/neo4j/v1/api.py", line 546, in __exit__
    self.close()
  File "/home/ubuntu/.virtualenvs/orca/lib/python3.5/site-packages/neo4j/v1/api.py", line 625, in close
    self.session.rollback_transaction()
  File "/home/ubuntu/.virtualenvs/orca/lib/python3.5/site-packages/neo4j/v1/api.py", line 457, in rollback_transaction
    self.__rollback__().consume()
  File "/home/ubuntu/.virtualenvs/orca/lib/python3.5/site-packages/neo4j/v1/api.py", line 738, in consume
    list(self)
  File "/home/ubuntu/.virtualenvs/orca/lib/python3.5/site-packages/neo4j/v1/api.py", line 706, in records
    keys = self.keys()
  File "/home/ubuntu/.virtualenvs/orca/lib/python3.5/site-packages/neo4j/v1/api.py", line 694, in keys
    self._session.send()
  File "/home/ubuntu/.virtualenvs/orca/lib/python3.5/site-packages/neo4j/v1/api.py", line 346, in send
    self._connection.send()
  File "/home/ubuntu/.virtualenvs/orca/lib/python3.5/site-packages/neo4j/bolt/connection.py", line 263, in send
    self._send()
  File "/home/ubuntu/.virtualenvs/orca/lib/python3.5/site-packages/neo4j/bolt/connection.py", line 275, in _send
    raise self.Error("Failed to write to closed connection {!r}".format(self.server.address))
neo4j.exceptions.ServiceUnavailable: Failed to write to closed connection Address(host='<_neo4j instance addr_>', port=7687)
10/25/2017 04:40:04 AM ERROR:Failed to write to closed connection Address(host='<_neo4j instance addr_>', port=7687)```
