### ISSUE TITLE
Bolt session "timeout" during retrieval of larger datasets

### ISSUE THREAD

**Issue by sntobaue** [neo4j/neo4j-python-driver#145]
I'm using Neo4j 3.1.1 community edition on a Windows 10 host. I'm trying to fetch roughly 80 million entries from the db via python 3.5.2 using the officialy supported python driver. The python script is running against localhost, i.e. on the same machine as Neo4j and not over network. Access to Neo4j works all fine until it comes to assembling the desired `property_list`:

    from neo4j.v1 import GraphDatabase, basic_auth   
    driver = GraphDatabase.driver("bolt://localhost:7687", auth=basic_auth(....))
    session = driver.session()
    result = session.run("match (n:Label) return n.Property as property")
    property_list = [record["property"] for record in result]

Assembling the `property_list` fails with the error statement:

> Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "<stdin>", line 1, in <listcomp>
  File "C:\Users\thbauer\Anaconda3\envs\rdkit-env\lib\site-packages\neo4j\v1\api.py", line 443, in records
    self.fetch()
  File "C:\Users\thbauer\Anaconda3\envs\rdkit-env\lib\site-packages\neo4j\v1\api.py", line 409, in fetch
    return self._session.fetch()
  File "C:\Users\thbauer\Anaconda3\envs\rdkit-env\lib\site-packages\neo4j\v1\bolt.py", line 151, in fetch
    return self.connection.fetch()
  File "C:\Users\thbauer\Anaconda3\envs\rdkit-env\lib\site-packages\neo4j\bolt\connection.py", line 373, in fetch
    message_data = self.buffering_socket.read_message()
  File "C:\Users\thbauer\Anaconda3\envs\rdkit-env\lib\site-packages\neo4j\bolt\connection.py", line 132, in read_message
    self.fill()
  File "C:\Users\thbauer\Anaconda3\envs\rdkit-env\lib\site-packages\neo4j\bolt\connection.py", line 124, in fill
    raise ServiceUnavailable("Failed to read from connection %r" % (self.address,))
neo4j.bolt.connection.ServiceUnavailable: Failed to read from connection Address(host='127.0.0.1', port=7687)

The error is easily and "reliably" reproducable. It is not occuring when I access less information, e.g. try to fetch only a few hundred entries.

Trying to run `result = session.run("match (n:Label) return n.Property as property")` for a smaller set of `n:Label` immediately after this error, results in another message:

> Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\thbauer\Anaconda3\envs\rdkit-env\lib\site-packages\neo4j\v1\bolt.py", line 130, in run
    raise SessionError("This session is closed.")
neo4j.v1.api.SessionError: This session is closed.

This issue is related to a question on stackoverflow: http://stackoverflow.com/questions/42930969/how-to-keep-a-neo4j-bolt-session-open

Update: on Linux the error message is: 

> Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.4/dist-packages/neo4j/v1/api.py", line 663, in records
    self._session.fetch()
  File "/usr/local/lib/python3.4/dist-packages/neo4j/v1/api.py", line 321, in fetch
    detail_count, _ = self._connection.fetch()
  File "/usr/local/lib/python3.4/dist-packages/neo4j/bolt/connection.py", line 255, in fetch
    self._receive()
  File "/usr/local/lib/python3.4/dist-packages/neo4j/bolt/connection.py", line 290, in _receive
    raise self.Error("Failed to read from defunct connection {!r}".format(self.server.address))
neo4j.exceptions.ServiceUnavailable: Failed to read from defunct connection Address(host='127.0.0.1', port=7687)

**Comment by john-bodley** [comment]
Note this may be related to https://github.com/neo4j/neo4j-python-driver/issues/143.

**Comment by technige** [comment]
@sntobaue Are you seeing anything in your server log, such as an `OutOfMemoryError`?

**Comment by zhenlineo** [comment]
Hi @sntobaue,

We have not hear from you for a while. Do you still have the problem? Have you tried with the latest 1.5 driver? Is there any error on the server side when you see this error?

I am closing this issue due to lack of more information to continue investigation. 
Please reach back to us if the problem still bothers you and reopen this issue.

Thanks,
Zhen
