### ISSUE TITLE
neo4j.exceptions.ClientError: Couldn't load the external resource at: file:/var/lib/neo4j/import/TagsSheet1.csv

### ISSUE THREAD

**Issue by naisanza** [neo4j/neo4j-python-driver#153]
I am not sure why I'm unable to use `LOAD CSV` even with the setting enabled, and read access to the file allowed as well.

CSV file stored:

`/var/lib/neo4j/import/TagsSheet1.csv`

neo4j.conf:

`dbms.security.allow_csv_import_from_file_urls=true`

Python script:

```
import neo4j
from neo4j.v1 import GraphDatabase, basic_auth

server = 'bolt://10.200.0.109:'
user = 'neo4j'
password = 'neo4j'

driver = GraphDatabase.driver(server, auth=basic_auth(user, password))
session = driver.session()

query = '''
LOAD CSV WITH HEADERS FROM "file:///{fpath}" AS heading 
MERGE (file:File {{name: heading.File}}) 
'''.format(fpath='Tags-Sheet1.csv')
```

Error:

```
Traceback (most recent call last):
  File "/usr/lib/python3.5/code.py", line 91, in runcode
    exec(code, self.locals)
  File "<input>", line 1, in <module>
  File "/home/eric/.local/lib/python3.5/site-packages/neo4j/v1/api.py", line 305, in run
    self._connection.fetch()
  File "/home/eric/.local/lib/python3.5/site-packages/neo4j/bolt/connection.py", line 276, in fetch
    response.on_failure(summary_metadata or {})
  File "/home/eric/.local/lib/python3.5/site-packages/neo4j/v1/result.py", line 69, in on_failure
    raise CypherError.hydrate(**metadata)
neo4j.exceptions.ClientError: Couldn't load the external resource at: file:/var/lib/neo4j/import/Tags-Sheet1.csv
```

**Comment by naisanza** [comment]
Hah. Okay so the `LOAD CSV` is looking for the file on the Neo4j instance, and not where the script is being executed. 

Boy that was dumb
