### ISSUE TITLE
Exception Argument 'b' has incorrect type (expected bytes, got SafeBytes))

### ISSUE THREAD

**Issue by g3rd** [neo4j/neo4j-python-driver#177]
MacOS 11 and Debian GNU/Linux 8 (jessie)
Python == 3.6 (also 3.5)
Django == 1.10.7
neo4j-driver == 1.4.0
Neo4j 3.2.3 Enterprise (production) and Neo4j 3.2.2 Community
I've seen similar errors on 3.1.x Enterprise, thus I upgraded.

Some of my queries throw the following exception.
```
Argument 'b' has incorrect type (expected bytes, got SafeBytes)
```

```
File "/usr/local/lib/python3.6/site-packages/neo4j/v1/api.py" in run
  336.         result = self.__run__(fix_statement(statement), fix_parameters(parameters, **kwparameters))

File "/usr/local/lib/python3.6/site-packages/neo4j/v1/session.py" in __run__
  53.         return self._run(statement, parameters)

File "/usr/local/lib/python3.6/site-packages/neo4j/v1/session.py" in _run
  45.             self._connection.append(RUN, (statement, parameters), response=run_response)

File "/usr/local/lib/python3.6/site-packages/neo4j/bolt/connection.py" in append
  220.         self.packer.pack_struct(signature, fields)

Exception Value: Argument 'b' has incorrect type (expected bytes, got SafeBytes)
```

### Things I have tried
1. Downgrading neo4j-driver versions
2. Upgrading the Python version from 3.5 to 3.6
3. Added a transaction like the example on http://neo4j.com/docs/api/python-driver/current/
4. Upgraded Neo4j

**Comment by g3rd** [comment]
In my production Neo4j Logs:

```
neo4j application_server 2017-08-15 21:33:02.156+0000 ERROR [o.n.b.v.t.BoltProtocolV1] Failed to handle incoming Bolt message. Connection will be closed. Unable to deserialize request, message boundary found before message ended. This indicates a serialization or framing problem with your client driver.
neo4j application_server org.neo4j.bolt.v1.messaging.BoltIOException: Unable to deserialize request, message boundary found before message ended. This indicates a serialization or framing problem with your client driver.
neo4j application_server at org.neo4j.bolt.v1.transport.ChunkedInput.ensureChunkAvailable(ChunkedInput.java:211)
neo4j application_server at org.neo4j.bolt.v1.transport.ChunkedInput.readBytes(ChunkedInput.java:171)
neo4j application_server at org.neo4j.bolt.v1.transport.ChunkedInput.readBytes(ChunkedInput.java:182)
neo4j application_server at org.neo4j.bolt.v1.packstream.PackStream$Unpacker.unpackRawBytesInto(PackStream.java:749)
neo4j application_server at org.neo4j.bolt.v1.packstream.PackStream$Unpacker.unpackRawBytes(PackStream.java:740)
neo4j application_server at org.neo4j.bolt.v1.packstream.PackStream$Unpacker.unpackUTF8(PackStream.java:687)
neo4j application_server at org.neo4j.bolt.v1.packstream.PackStream$Unpacker.unpackString(PackStream.java:607)
neo4j application_server at org.neo4j.bolt.v1.messaging.Neo4jPack$Unpacker.unpack(Neo4jPack.java:280)
neo4j application_server at org.neo4j.bolt.v1.messaging.Neo4jPack$Unpacker.unpackMap(Neo4jPack.java:440)
neo4j application_server at org.neo4j.bolt.v1.messaging.BoltRequestMessageReader.read(BoltRequestMessageReader.java:77)
neo4j application_server at org.neo4j.bolt.v1.transport.BoltV1Dechunker.handleHeader(BoltV1Dechunker.java:138)
neo4j application_server at org.neo4j.bolt.v1.transport.BoltV1Dechunker.handle(BoltV1Dechunker.java:74)
neo4j application_server at org.neo4j.bolt.v1.transport.BoltProtocolV1.handle(BoltProtocolV1.java:79)
neo4j application_server at org.neo4j.bolt.transport.SocketTransportHandler.channelRead(SocketTransportHandler.java:62)
neo4j application_server at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:363)
neo4j application_server at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:349)
neo4j application_server at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:341)
neo4j application_server at io.netty.handler.ssl.SslHandler.unwrap(SslHandler.java:1228)
neo4j application_server at io.netty.handler.ssl.SslHandler.decode(SslHandler.java:1039)
neo4j application_server at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:411)
neo4j application_server at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:248)
neo4j application_server at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:363)
neo4j application_server at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:349)
neo4j application_server at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:341)
neo4j application_server at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1334)
neo4j application_server at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:363)
neo4j application_server at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:349)
neo4j application_server at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:926)
neo4j application_server at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:129)
neo4j application_server at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:642)
neo4j application_server at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:565)
neo4j application_server at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:479)
neo4j application_server at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:441)
neo4j application_server at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858)
neo4j application_server at java.lang.Thread.run(Thread.java:745)
neo4j application_server 2017-08-15 21:33:32.844+0000 INFO [o.n.k.i.t.l.c.CheckPointerImpl] Check Pointing triggered by scheduler for time threshold [763712]: Starting check pointing...
neo4j application_server 2017-08-15 21:33:32.844+0000 INFO [o.n.k.i.t.l.c.CheckPointerImpl] Check Pointing triggered by scheduler for time threshold [763712]: Starting store flush...
neo4j application_server 2017-08-15 21:33:32.846+0000 INFO [o.n.k.i.s.c.CountsTracker] About to rotate counts store at transaction 763712 to [/opt/neo4j/data/databases/graph.db/neostore.counts.db.a], from [/opt/neo4j/data/databases/graph.db/neostore.counts.db.b].
neo4j application_server 2017-08-15 21:33:32.856+0000 INFO [o.n.k.i.s.c.CountsTracker] Successfully rotated counts store at transaction 763712 to [/opt/neo4j/data/databases/graph.db/neostore.counts.db.a], from [/opt/neo4j/data/databases/graph.db/neostore.counts.db.b].
neo4j application_server 2017-08-15 21:33:32.871+0000 INFO [o.n.k.i.t.l.c.CheckPointerImpl] Check Pointing triggered by scheduler for time threshold [763712]: Store flush completed
neo4j application_server 2017-08-15 21:33:32.871+0000 INFO [o.n.k.i.t.l.c.CheckPointerImpl] Check Pointing triggered by scheduler for time threshold [763712]: Starting appending check point entry into the tx log...
neo4j application_server 2017-08-15 21:33:32.873+0000 INFO [o.n.k.i.t.l.c.CheckPointerImpl] Check Pointing triggered by scheduler for time threshold [763712]: Appending check point entry into the tx log completed
neo4j application_server 2017-08-15 21:33:32.873+0000 INFO [o.n.k.i.t.l.c.CheckPointerImpl] Check Pointing triggered by scheduler for time threshold [763712]: Check pointing completed
neo4j application_server 2017-08-15 21:33:32.873+0000 INFO [o.n.k.i.t.l.p.LogPruningImpl] Log Rotation [4]: Starting log pruning.
neo4j application_server 2017-08-15 21:33:32.873+0000 INFO [o.n.k.i.t.l.p.LogPruningImpl] Log Rotation [4]: Log pruning complete.
neo4j application_server 2017-08-15 21:35:58.658+0000 ERROR [o.n.b.v.t.BoltProtocolV1] Failed to handle incoming Bolt message. Connection will be closed. Unable to read message type. Error was: Bad key type: INTEGER
neo4j application_server org.neo4j.bolt.v1.messaging.BoltIOException: Unable to read message type. Error was: Bad key type: INTEGER
neo4j application_server at org.neo4j.bolt.v1.messaging.BoltRequestMessageReader.read(BoltRequestMessageReader.java:108)
neo4j application_server at org.neo4j.bolt.v1.transport.BoltV1Dechunker.handleHeader(BoltV1Dechunker.java:138)
neo4j application_server at org.neo4j.bolt.v1.transport.BoltV1Dechunker.handle(BoltV1Dechunker.java:74)
neo4j application_server at org.neo4j.bolt.v1.transport.BoltProtocolV1.handle(BoltProtocolV1.java:79)
neo4j application_server at org.neo4j.bolt.transport.SocketTransportHandler.channelRead(SocketTransportHandler.java:62)
neo4j application_server at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:363)
neo4j application_server at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:349)
neo4j application_server at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:341)
neo4j application_server at io.netty.handler.ssl.SslHandler.unwrap(SslHandler.java:1228)
neo4j application_server at io.netty.handler.ssl.SslHandler.decode(SslHandler.java:1039)
neo4j application_server at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:411)
neo4j application_server at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:248)
neo4j application_server at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:363)
neo4j application_server at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:349)
neo4j application_server at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:341)
neo4j application_server at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1334)
neo4j application_server at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:363)
neo4j application_server at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:349)
neo4j application_server at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:926)
neo4j application_server at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:129)
neo4j application_server at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:642)
neo4j application_server at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:565)
neo4j application_server at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:479)
neo4j application_server at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:441)
neo4j application_server at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858)
neo4j application_server at java.lang.Thread.run(Thread.java:745)
neo4j application_server Caused by: org.neo4j.bolt.v1.packstream.PackStream$PackStreamException: Bad key type: INTEGER
neo4j application_server at org.neo4j.bolt.v1.messaging.Neo4jPack$Unpacker.unpackMap(Neo4jPack.java:437)
neo4j application_server at org.neo4j.bolt.v1.messaging.BoltRequestMessageReader.read(BoltRequestMessageReader.java:77)
neo4j application_server ... 25 more
```

**Comment by technige** [comment]
There is no class in the driver called `SafeBytes`. A quick Google shows such a class belonging to Django however (`django.utils.safestring.SafeBytes`) so this must be interfering somehow. Though I'm not sure how as these values should all be generated internally.

Unless Django does some kind of monkey-patching...
