### ISSUE TITLE
Add more detailed exception message

### ISSUE THREAD

**Issue by B-Stefan** [neo4j/neo4j-python-driver#183]
I got the problem that the neo4j-driver throws an expcetion in the [travis enviroment](https://travis-ci.org/DLR-SC/prov-db-connector/builds/255251419#L958) that could be improved. 
Especially the message ;)   

I got the following error message: 

```
Traceback (most recent call last):
  File "/home/travis/build/DLR-SC/prov-db-connector/provdbconnector/tests/db_adapters/test_baseadapter.py", line 515, in test_8_get_records_by_filter
    raw_result = self.instance.get_records_by_filter()
  File "/home/travis/build/DLR-SC/prov-db-connector/provdbconnector/db_adapters/neo4j/neo4jadapter.py", line 394, in get_records_by_filter
    for result in result_set:
  File "/home/travis/virtualenv/python3.5.3/lib/python3.5/site-packages/neo4j/v1/api.py", line 437, in records
    keys = self.keys()
  File "/home/travis/virtualenv/python3.5.3/lib/python3.5/site-packages/neo4j/v1/api.py", line 427, in keys
    self.fetch()
  File "/home/travis/virtualenv/python3.5.3/lib/python3.5/site-packages/neo4j/v1/api.py", line 409, in fetch
    return self._session.fetch()
  File "/home/travis/virtualenv/python3.5.3/lib/python3.5/site-packages/neo4j/v1/bolt.py", line 151, in fetch
    return self.connection.fetch()
  File "/home/travis/virtualenv/python3.5.3/lib/python3.5/site-packages/neo4j/bolt/connection.py", line 407, in fetch
    response.on_failure(metadata or {})
  File "/home/travis/virtualenv/python3.5.3/lib/python3.5/site-packages/neo4j/v1/bolt.py", line 222, in on_failure
    raise self.error_class(metadata)
neo4j.v1.api.CypherError: Internal error - should have used fall back to execute query, but something went horribly wrong
``` 

Do you have any idea what could cause this exception?

**Comment by zhenlineo** [comment]
Hi @B-Stefan,

I tried to search in the whole driver codebase, but I did not find anything related to this error message.
And also you seems on a old 1.1 driver, could you try to update to the latest driver and retry your test?

I am closing this issue as I cannot find the error message from the driver code. Either because we already fixed or it is an external error.

Best,
Zhen
