### ISSUE TITLE
when i run pass_bookmarks_example.py ,i got the following error, what am i doing wrong?

### ISSUE THREAD

**Issue by pangguoming** [neo4j/neo4j-python-driver#249]
D:\PythonWorkspace\test\venv\Scripts\python.exe D:/PythonWorkspace/test/pass_bookmarks_example.py
Traceback (most recent call last):
  File "D:\PythonWorkspace\test\venv\lib\site-packages\neo4j\v1\api.py", line 56, in last_bookmark
    n[i] = int(n[i])
ValueError: invalid literal for int() with base 10: 'tx46'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:/PythonWorkspace/test/pass_bookmarks_example.py", line 68, in <module>
    exam.main()
  File "D:/PythonWorkspace/test/pass_bookmarks_example.py", line 62, in main
    session_c.write_transaction(self.create_friendship, "Alice", "Bob")
  File "D:\PythonWorkspace\test\venv\lib\site-packages\neo4j\v1\api.py", line 497, in write_transaction
    return self._run_transaction(WRITE_ACCESS, unit_of_work, *args, **kwargs)
  File "D:\PythonWorkspace\test\venv\lib\site-packages\neo4j\v1\api.py", line 462, in _run_transaction
    self.__begin__()
  File "D:\PythonWorkspace\test\venv\lib\site-packages\neo4j\v1\api.py", line 522, in __begin__
    parameters = {"bookmark": self.last_bookmark(), "bookmarks": self._bookmarks}
  File "D:\PythonWorkspace\test\venv\lib\site-packages\neo4j\v1\api.py", line 384, in last_bookmark
    last = last_bookmark(last, bookmark)
  File "D:\PythonWorkspace\test\venv\lib\site-packages\neo4j\v1\api.py", line 58, in last_bookmark
    raise ValueError("Invalid bookmark: {}".format(b0))
ValueError: Invalid bookmark: `neo4j:bookmark:v1:tx46`

Process finished with exit code 1

**Comment by zhenlineo** [comment]
Hi @pangguoming 

The bookmark format looks correct and our bookmark tests seems working as normal too.

Which neo4j version that you are using to run this test against? Are you running this test direct with the latest source code?

Regards,
Zhen

**Comment by zhenlineo** [comment]
Seems a bug. Thanks for reporting. We will have a deeper look at it.

**Comment by pangguoming** [comment]
i use latest  version 1.6.0
