### ISSUE TITLE
neo4j.v1.exceptions.ProtocolError: Server closed connection

### ISSUE THREAD

**Issue by bingosxs** [neo4j/neo4j-python-driver#252]
I got this error when I run the following example code from the guide.
**The bizarreness is that it runs normally if I use python3.**
```
from neo4j.v1 import GraphDatabase

uri = "bolt://localhost:7687"
driver = GraphDatabase.driver(uri, auth=("neo4j", "password"))

def print_friends_of(tx, name):
    for record in tx.run("MATCH (a:Person)-[:KNOWS]->(f) "
                         "WHERE a.name = {name} "
                         "RETURN f.name", name=name):
        print(record["f.name"])

with driver.session() as session:
    session.read_transaction(print_friends_of, "Alice")
```
The versions of related envs:

1.   `Python 2.7.12 (default, Dec  4 2017, 14:50:18) `

2. neo4j-community-3.4.1
 
3. The neo4j is started by:
  `neo4j-community-3.4.1/bin/neo4j start`

neo4j-driver is installed by  pip tool.

**Comment by technige** [comment]
I'm unable to recreate the problem using the versions you describe. There has to be an environmental factor at play here - maybe a firewall issue or a misconfigured server?

**Comment by Cr0n1c** [comment]
I am encountering the same problem.

This is my remote computer [Windows 10 fully patched as of 9/22/2018 x64] [172.16.0.4]
```
Python 2.7.14 (v2.7.14:84471935ed, Sep 16 2017, 20:19:30) [MSC v.1500 32 bit (Intel)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import py2neo
>>> print py2neo.__version__
3.1.2
>>> py2neo.authenticate("10.10.10.15:7473", "neo4j", "neo4j_password_changed")
>>> py2neo.Graph(host="10.10.10.15", secure=True)
<Graph uri=u'https://10.10.10.15:7473/db/data/'>
>>> py2neo.Graph(host="10.10.10.15", secure=True).data("MATCH (a) RETURN a LIMIT 1")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "c:\python27\lib\site-packages\py2neo\database\__init__.py", line 416, in data
    return self.begin(autocommit=True).run(statement, parameters, **kwparameters).data()
  File "c:\python27\lib\site-packages\py2neo\database\__init__.py", line 370, in begin
    return self.transaction_class(self, autocommit)
  File "c:\python27\lib\site-packages\py2neo\database\__init__.py", line 1249, in __init__
    self.session = driver.session()
  File "c:\python27\lib\site-packages\py2neo\packages\neo4j\v1\session.py", line 126, in session
    connection = connect(self.address, self.ssl_context, **self.config)
  File "c:\python27\lib\site-packages\py2neo\packages\neo4j\v1\bolt.py", line 482, in connect
    return Connection(s, der_encoded_server_certificate=der_encoded_server_certificate, **config)
  File "c:\python27\lib\site-packages\py2neo\packages\neo4j\v1\bolt.py", line 241, in __init__
    self.fetch()
  File "c:\python27\lib\site-packages\py2neo\packages\neo4j\v1\bolt.py", line 337, in fetch
    self.acknowledge_failure()
  File "c:\python27\lib\site-packages\py2neo\packages\neo4j\v1\bolt.py", line 284, in acknowledge_failure
    fetch()
  File "c:\python27\lib\site-packages\py2neo\packages\neo4j\v1\bolt.py", line 322, in fetch
    raw.writelines(self.channel.chunk_reader())
  File "c:\python27\lib\site-packages\py2neo\packages\neo4j\v1\bolt.py", line 173, in chunk_reader
    chunk_header = self._recv(2)
  File "c:\python27\lib\site-packages\py2neo\packages\neo4j\v1\bolt.py", line 156, in _recv
    raise ProtocolError("Server closed connection")
py2neo.packages.neo4j.v1.exceptions.ProtocolError: Server closed connection
>>>
```

This is the same computer browsing to the neo4j instance in a browser.
![image](https://user-images.githubusercontent.com/5178129/45919813-96769f00-be69-11e8-8772-12ef24e2803d.png)

![image](https://user-images.githubusercontent.com/5178129/45919871-56fc8280-be6a-11e8-85cf-23a512b6b81e.png)

This is the actual server hosting neo4j [10.10.10.15].

uname -a 
cat /etc/*release
 netstat -anop |grep -e "7473\|7687"

```uname -a && cat /etc/*release && netstat -anop|grep -e "7473\|7687"
Linux dev-neo4j 3.10.0-862.el7.x86_64 #1 SMP Fri Apr 20 16:44:24 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
CentOS Linux release 7.5.1804 (Core)
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"

CentOS Linux release 7.5.1804 (Core)
CentOS Linux release 7.5.1804 (Core)
tcp6       0      0 :::7687                 :::*                    LISTEN      13426/java           off (0.00/0/0)
tcp6       0      0 :::7473                 :::*                    LISTEN      13426/java           off (0.00/0/0)
tcp6       0      0 10.10.10.15:7687       172.16.0.4:49984        TIME_WAIT   -                    timewait (8.13/0/0)
tcp6       0      0 10.10.10.15:7687       172.16.0.4:61552        ESTABLISHED 13426/java           off (0.00/0/0)
tcp6       0      0 10.10.10.15:7687       172.16.0.4:56562        ESTABLISHED 13426/java           off (0.00/0/0)
tcp6       0      0 10.10.10.15:7687       172.16.0.4:49988        TIME_WAIT   -                    timewait (9.11/0/0)
tcp6       0      0 10.10.10.15:7687       172.16.0.4:50054        TIME_WAIT   -                    timewait (49.11/0/0)
tcp6       0      0 10.10.10.15:7687       172.16.0.4:50020        TIME_WAIT   -                    timewait (28.00/0/0)
tcp6       0      0 10.10.10.15:7687       172.16.0.4:50024        TIME_WAIT   -                    timewait (28.91/0/0)
tcp6       0      0 10.10.10.15:7687       172.16.0.4:65520        ESTABLISHED 13426/java           off (0.00/0/0)
tcp6       0      0 10.10.10.15:7687       172.16.0.4:59757        ESTABLISHED 13426/java           off (0.00/0/0)
tcp6       0      0 10.10.10.15:7687       172.16.0.4:50058        TIME_WAIT   -                    timewait (50.07/0/0)
tcp6       0      0 10.10.10.15:7687       172.16.0.4:51768        ESTABLISHED 13426/java           off (0.00/0/0)
tcp6       0      0 10.10.10.15:7687       172.16.0.4:49983        TIME_WAIT   -                    timewait (7.97/0/0)
tcp6       0      0 10.10.10.15:7687       172.16.0.4:50053        TIME_WAIT   -                    timewait (48.97/0/0)
tcp6       0      0 10.10.10.15:7687       172.16.0.4:61541        ESTABLISHED 13426/java           off (0.00/0/0)
tcp6       0      0 10.10.10.15:7687       172.16.0.4:50019        TIME_WAIT   -                    timewait (27.76/0/0)
tcp6       0      0 10.10.10.15:7687       172.16.0.4:59192        ESTABLISHED 13426/java           off (0.00/0/0)```

**Comment by technige** [comment]
@ChiefyChief Your code shows that you are using py2neo 3.1.2, which embeds a very old version of the official driver (1.1). As you are using this against a much newer server (3.4.1) then odd errors such as this are not hugely surprising. For context, the 1.1 driver was released in October 2016, whereas the 3.4 server comes from April 2018 (in tandem with the 1.6 driver).

You will therefore need to either downgrade your server version or (much better) upgrade your driver. Py2neo v4 has been out for a while now and uses the much more up-to-date 1.6 official driver.

**Comment by Cr0n1c** [comment]
Cool, I thought I had upgraded py2neo via Pip but just realized that it is broken [at least for Python 2.7.x]

I manually went in to fix the error and my other issue disappeared.

```PS C:\> pip install pip --upgrade
Requirement already up-to-date: pip in c:\python27\lib\site-packages (18.0)

PS C:\> pip install py2neo --upgrade
Collecting py2neo
  Using cached https://files.pythonhosted.org/packages/02/18/1880df5c6f4c0a6aa598286541c7c5a287dc5150d28e05595ec4197e8402/py2neo-4.1.0.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "c:\users\bhelm\appdata\local\temp\pip-install-meccfd\py2neo\setup.py", line 25, in <module>
        from py2neo.meta import __author__, __email__, __license__, __package__, __version__
      File "py2neo\__init__.py", line 19, in <module>
        from py2neo.data import *
      File "py2neo\data.py", line 26, in <module>
        from py2neo.cypher import cypher_repr, cypher_str
      File "py2neo\cypher\__init__.py", line 25, in <module>
        from py2neo.cypher.encoding import CypherEncoder
      File "py2neo\cypher\encoding.py", line 30, in <module>
        from py2neo.internal.collections import SetView
      File "py2neo\internal\collections.py", line 24, in <module>
        from py2neo.internal.compat import bytes_types, string_types
      File "py2neo\internal\compat.py", line 45, in <module>
        DEVNULL = open(devnull, "rw")
    ValueError: Invalid mode ('rw')

    ----------------------------------------```

**Comment by technige** [comment]
@ChiefyChief Can I suggest that you raise any py2neo-related issues against that project repository? I can't deal with them here unfortunately.

@bingosxs  To diagnose your original problem, I'll need more information about your setup. The example code on its own generally works. Given that you've not yet been able to provide any extra info, I'm going to close the issue for now. Please reopen if you're able to help us recreate the problem.
