### ISSUE TITLE
Session.__exit__ tries to sync using a broken connection.

### ISSUE THREAD

**Issue by ecdavis** [neo4j/neo4j-python-driver#301]
## `Session.__exit__` tries to sync using a broken connection.

**Neo4j version:** Community 3.5.11
**Neo4j Mode:** Single instance
**Driver version:** Python driver 1.7.0
**Operating system:** Ubuntu 14.04.6 LTS on AWS

### Steps to reproduce
This one is hard to repro, as it requires neo4j to close a Bolt connection. I discovered it while debugging this behavior: https://github.com/neo4j/neo4j/issues/11997 -- one of my queries got "stuck" for long enough that neo4j drops the connection, which causes the driver to crash unceremoniously. Here's the code I was running, if it helps: https://github.com/lyft/cartography/blob/0.10.0/cartography/intel/aws/ec2.py#L181-L252

1. Run a query using the following pattern:
```python
with driver.session() as session:
    session.run(query)
```
2. During execution of the query, trigger a `ConnectionResetError` in `session._connection.send` -- this can occur when neo4j closes the connection unexpectedly.

### Expected behavior
Only `ConnectionResetError` should bubble up to the caller.

### Actual behavior
`BrokenPipeError` occurs during execution of `Session.__exit__`, then a `NameError` occurs during handling of the `BrokenPipeError`.

Looking through the code:
1. https://github.com/neo4j/neo4j-python-driver/blob/1.7/neo4j/__init__.py#L498 if a `ConnectionResetError` occurs during this `send` call, it will not be handled and will bubble up to the caller. I don't think this is necessarily a bad thing, but;
2. Because the exception is bubbling upwards, Python cleans up the `with` block, which calls `Session.__exit__`: https://github.com/neo4j/neo4j-python-driver/blob/1.7/neo4j/__init__.py#L369
3. `Session.__exit__` calls `Session.close`: https://github.com/neo4j/neo4j-python-driver/blob/1.7/neo4j/__init__.py#L386
4. The `Session._connection` object is not `None`, so `close` will try to call `sync`: https://github.com/neo4j/neo4j-python-driver/blob/1.7/neo4j/__init__.py#L395
5. `sync` raises a `BrokenPipeError` because the underlying connection is closed.

#### Neo4j Driver Stack Trace
```
Traceback (most recent call last):
  ...
  File ".../lib/python3.6/site-packages/neo4j/__init__.py", line 498, in run
    self._connection.send()
  File ".../lib/python3.6/site-packages/neobolt/direct.py", line 394, in send
    self._send()
  File ".../lib/python3.6/site-packages/neobolt/direct.py", line 409, in _send
    self.socket.sendall(data)
  File "/usr/lib/python3.6/ssl.py", line 965, in sendall
    v = self.send(data[count:])
  File "/usr/lib/python3.6/ssl.py", line 935, in send
    return self._sslobj.write(data)
  File "/usr/lib/python3.6/ssl.py", line 636, in write
    return self._sslobj.write(data)
ConnectionResetError: [Errno 104] Connection reset by peer

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File ".../lib/python3.6/site-packages/neo4j/__init__.py", line 395, in close
    self._connection.sync()
  File ".../lib/python3.6/site-packages/neobolt/direct.py", line 505, in sync
    self.send()
  File ".../lib/python3.6/site-packages/neobolt/direct.py", line 394, in send
    self._send()
  File ".../lib/python3.6/site-packages/neobolt/direct.py", line 409, in _send
    self.socket.sendall(data)
  File "/usr/lib/python3.6/ssl.py", line 965, in sendall
    v = self.send(data[count:])
  File "/usr/lib/python3.6/ssl.py", line 935, in send
    return self._sslobj.write(data)
  File "/usr/lib/python3.6/ssl.py", line 636, in write
    return self._sslobj.write(data)
BrokenPipeError: [Errno 32] Broken pipe

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  ...
  File ".../lib/python3.6/site-packages/neo4j/__init__.py", line 370, in __exit__
    self.close()
  File ".../lib/python3.6/site-packages/neo4j/__init__.py", line 397, in close
    ServiceUnavailable, SessionError):
NameError: name 'ServiceUnavailable' is not defined
```

**Comment by technige** [comment]
Can you try with the latest 1.7 patch?

**Comment by zhenlineo** [comment]
Ping @ecdavis ^^

**Comment by zhenlineo** [comment]
Hi @ecdavis,

I am closing this issue as we have not heard back from you. Please let us know if this is still a problem for you and provide us more information to continue.

Cheers,
Zhen
