### ISSUE TITLE
connection timed out while using read_transaction()

### ISSUE THREAD

**Issue by ghost** [neo4j/neo4j-python-driver#315]
### always occurs after a certain time
and this is recorded by logger in neo4j
```
Failed to write data to connection Address(host='', port=7687) (Address(host='', port=7687)); ("110; 'Connection timed out'")
```
this is debug.log
```
ERROR [o.n.b.t.p.HouseKeeper] Fatal error occurred when handling a client connection: [id: 0x4ddc3bca, L:/ - R:/] readAddress(..) failed: Connection timed out
io.netty.channel.unix.Errors$NativeIoException: readAddress(..) failed: Connection timed out
        at io.netty.channel.unix.Errors.newIOException(Errors.java:122)
        at io.netty.channel.unix.Errors.ioResult(Errors.java:146)
        at io.netty.channel.unix.FileDescriptor.readAddress(FileDescriptor.java:178)
        at io.netty.channel.epoll.AbstractEpollChannel.doReadBytes(AbstractEpollChannel.java:343)
        at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:785)
        at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:433)
        at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:330)
        at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:909)
        at java.lang.Thread.run(Thread.java:748)
```
is it right?
```
...
self._open_transaction()
tx = self._transaction # get transaction
...
result = unit_of_work(...) # transacton.run()
...
session.run()
...
```
but it seems like has_transaction() in session.run() would be False 
then self._connection.send() will call socket.send_all() where there will throw that exception
```
        if not has_transaction:
            try:
                self._connection.send()
                self._connection.fetch()
            except ConnectionExpired as error:
                raise SessionExpired(*error.args)
```
have no idea why transaction and connection would fail

**Comment by martin-neotech** [comment]
Please use the API as suggested in the example:

https://github.com/neo4j/neo4j-python-driver#quick-example

About the connection, that it times out, the infrastructure could be the case:

https://github.com/neo4j/neo4j-python-driver/issues/316#issuecomment-564020680

Configure the Bolt Pool on the server side:

https://neo4j.com/docs/operations-manual/current/performance/bolt-thread-pool-configuration/#_configuration_options
