### ISSUE TITLE
neobolt.exceptions.ServiceUnavailable: Failed to establish connection to ('::1', 8687, 0, 0) (reason [Errno 113] No route to host)

### ISSUE THREAD

**Issue by DachuanZhao** [neo4j/neo4j-python-driver#331]
I can't connect to neo4j when I use neo4j4.0.0 . Everything is OK when I use neo4j3.5.14 .
I'm sure that I have changed bolt port from 7687 to 8687 . When I telnet localhost 8687 , it' can connect
 
- Neo4j version: Community4.0.0
- Neo4j Mode: Single instance
- Driver version: python driver 1.7.6 
- Operating system: CentOS7.6
- **Steps to reproduce**
```
NEO4J_HOST = "localhost"
NEO4J_PORT = 8687
NEO4J_USERNAME = "neo4j"
NEO4J_PASSWORD = "neo4j"

NEO4J_URI = "bolt://{NEO4J_HOST}:{NEO4J_PORT}".format(NEO4J_HOST=NEO4J_HOST,NEO4J_PORT=NEO4J_PORT)

NEO4J_DRIVER = neo4j.GraphDatabase.driver(
    uri=NEO4J_URI,
    auth=(NEO4J_USERNAME, NEO4J_PASSWORD),
    max_connection_lifetime=30 * 60,
    max_connection_pool_size=150, 
    connection_acquisition_timeout=2 * 60,
    connection_timeout=3,
    max_retry_time=1,
    )
```

```
Traceback (most recent call last):
  File "/mnt/zhaodachuan/anaconda3/lib/python3.7/site-packages/neobolt/direct.py", line 831, in _connect
    s.connect(resolved_address)
OSError: [Errno 113] No route to host

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "neo4j01_import_entity.py", line 34, in <module>
    max_retry_time=1,
  File "/mnt/zhaodachuan/anaconda3/lib/python3.7/site-packages/neo4j/__init__.py", line 120, in driver
    return Driver(uri, **config)
  File "/mnt/zhaodachuan/anaconda3/lib/python3.7/site-packages/neo4j/__init__.py", line 161, in __new__
    return subclass(uri, **config)
  File "/mnt/zhaodachuan/anaconda3/lib/python3.7/site-packages/neo4j/__init__.py", line 235, in __new__
    pool.release(pool.acquire())
  File "/mnt/zhaodachuan/anaconda3/lib/python3.7/site-packages/neobolt/direct.py", line 715, in acquire
    return self.acquire_direct(self.address)
  File "/mnt/zhaodachuan/anaconda3/lib/python3.7/site-packages/neobolt/direct.py", line 608, in acquire_direct
    connection = self.connector(address, error_handler=self.connection_error_handler)
  File "/mnt/zhaodachuan/anaconda3/lib/python3.7/site-packages/neo4j/__init__.py", line 232, in connector
    return connect(address, **dict(config, **kwargs))
  File "/mnt/zhaodachuan/anaconda3/lib/python3.7/site-packages/neobolt/direct.py", line 972, in connect
    raise last_error
  File "/mnt/zhaodachuan/anaconda3/lib/python3.7/site-packages/neobolt/direct.py", line 962, in connect
    s = _connect(resolved_address, **config)
  File "/mnt/zhaodachuan/anaconda3/lib/python3.7/site-packages/neobolt/direct.py", line 843, in _connect
    raise ServiceUnavailable("Failed to establish connection to {!r} (reason {})".format(resolved_address, error))
neobolt.exceptions.ServiceUnavailable: Failed to establish connection to ('::1', 8687, 0, 0) (reason [Errno 113] No route to host)
```

- Expected behavior

- Actual behavior

**Comment by technige** [comment]
The error message indicates a networking issue on your side. As such, there's nothing we can really do to help you diagnose that.

In this case, you might have an IPv6 issue whereby `localhost` is resolving to `::1` but some part of your IPv6 stack is broken. You could try `127.0.0.1` instead of `localhost` to force IPv4. Other than that, it's likely to be a local networking issue that you'll have to investigate within your operating system.

**Comment by DachuanZhao** [comment]
> The error message indicates a networking issue on your side. As such, there's nothing we can really do to help you diagnose that.
> 
> In this case, you might have an IPv6 issue whereby is resolving to but some part of your IPv6 stack is broken. You could try instead of to force IPv4. Other than that, it's likely to be a local networking issue that you'll have to investigate within your operating system.`localhost``::1``127.0.0.1``localhost`

When I use ```0.0.0.0``` or ```127.0.0.1``` , it raise a different error :
```
Traceback (most recent call last):
  File "neo4j01_import_entity.py", line 36, in <module>
    max_retry_time=1,
  File "/mnt/zhaodachuan/anaconda3/lib/python3.7/site-packages/neo4j/__init__.py", line 120, in driver
    return Driver(uri, **config)
  File "/mnt/zhaodachuan/anaconda3/lib/python3.7/site-packages/neo4j/__init__.py", line 161, in __new__
    return subclass(uri, **config)
  File "/mnt/zhaodachuan/anaconda3/lib/python3.7/site-packages/neo4j/__init__.py", line 235, in __new__
    pool.release(pool.acquire())
  File "/mnt/zhaodachuan/anaconda3/lib/python3.7/site-packages/neobolt/direct.py", line 715, in acquire
    return self.acquire_direct(self.address)
  File "/mnt/zhaodachuan/anaconda3/lib/python3.7/site-packages/neobolt/direct.py", line 608, in acquire_direct
    connection = self.connector(address, error_handler=self.connection_error_handler)
  File "/mnt/zhaodachuan/anaconda3/lib/python3.7/site-packages/neo4j/__init__.py", line 232, in connector
    return connect(address, **dict(config, **kwargs))
  File "/mnt/zhaodachuan/anaconda3/lib/python3.7/site-packages/neobolt/direct.py", line 972, in connect
    raise last_error
  File "/mnt/zhaodachuan/anaconda3/lib/python3.7/site-packages/neobolt/direct.py", line 963, in connect
    s, der_encoded_server_certificate = _secure(s, host, security_plan.ssl_context, **config)
  File "/mnt/zhaodachuan/anaconda3/lib/python3.7/site-packages/neobolt/direct.py", line 854, in _secure
    s = ssl_context.wrap_socket(s, server_hostname=host if HAS_SNI and host else None)
  File "/mnt/zhaodachuan/anaconda3/lib/python3.7/ssl.py", line 412, in wrap_socket
    session=session
  File "/mnt/zhaodachuan/anaconda3/lib/python3.7/ssl.py", line 853, in _create
    self.do_handshake()
  File "/mnt/zhaodachuan/anaconda3/lib/python3.7/ssl.py", line 1117, in do_handshake
    self._sslobj.do_handshake()
OSError: [Errno 0] Error
```
I can use all of ```127.0.0.1 localhost 0.0.0.0``` when I use neo4j 3.5.14 . 

Neo4j 3.5.14's config is : 
```
# Bolt connector
dbms.connector.bolt.enabled=true
#dbms.connector.bolt.tls_level=OPTIONAL
dbms.connector.bolt.listen_address=:8687

```
Neo4j 4.0.0's config is : 
```

# Bolt connector
dbms.connector.bolt.enabled=true
#dbms.connector.bolt.tls_level=DISABLED
dbms.connector.bolt.listen_address=:8687
```

By the way ,can the latest neo4j-python-driver 1.7.6 be used for neo4j4.0.0 without any update ?

**Comment by zhenlineo** [comment]
Hi @DachuanZhao,

Your server config requires plaintext connections. 1.7 driver has encryption turned on by default. You can either turn encryption off on driver, or change server config to have encryption on by providing a cert to the server and changing `dbms.connector.bolt.tls_level=OPTIONAL`.

Cheers,
Zhen

**Comment by DachuanZhao** [comment]
> Hi @DachuanZhao,
> 
> Your server config requires plaintext connections. 1.7 driver has encryption turned on by default. You can either turn encryption off on driver, or change server config to have encryption on by providing a cert to the server and changing .`dbms.connector.bolt.tls_level=OPTIONAL`
> 
> Cheers,
> Zhen

That' all right . When I change config file from ```#dbms.connector.bolt.tls_level=OPTIONAL``` to ```dbms.connector.bolt.tls_level=DISABLED``` in Neo4j3.5.14 , it raises the same error . 
Is there any document for it ? Because when I change config file   from ```#dbms.connector.bolt.tls_level=OPTIONAL``` to ```dbms.connector.bolt.tls_level=DISABLED```  in Neo4j4.0.0 , it raises error 

```ERROR Failed to start Neo4j: Starting Neo4j failed: Component 'org.neo4j.server.database.LifecycleManagingDatabaseService@4da9f723' was successfully initialized, but failed to start. Please see the attached cause exception "No SSL policy has been configured for Bolt server". Starting Neo4j failed: Component 'org.neo4j.server.database.LifecycleManagingDatabaseService@4da9f723' was successfully initialized, but failed to start. Please see the attached cause exception "No SSL policy has been configured for Bolt server".```

**Comment by DachuanZhao** [comment]
> encryption

I don't find neo4j 4.0.0 document  on [website](https://neo4j.com/docs/operations-manual/) , But I change my code like this :
```
NEO4J_DRIVER = neo4j.GraphDatabase.driver(
    uri=NEO4J_URI,
    auth=(NEO4J_USERNAME, NEO4J_PASSWORD),
    encrypted = False, 
    max_connection_lifetime=30 * 60,
    max_connection_pool_size=150, 
    connection_acquisition_timeout=2 * 60,
    connection_timeout=3,
    max_retry_time=1,
    )
```
Thanks a lot !

**Comment by timkofu** [comment]
Setting `encrypted=False` worked for me as well on 4.0.0.

**Comment by kumaF** [comment]
Setting `encrypted=False` saved my day as well :D
