### ISSUE TITLE
neobolt.exceptions.SecurityError on OSX

### ISSUE THREAD

**Issue by GodsDusk** [neo4j/neo4j-python-driver#354]
- Neo4j version: 3.5.3 Enterprise
- Neo4j Mode: Single instance
- python version: 3.5.4 
- Driver version: python driver 1.7.6
- Operating system: macOS Mojave 10.14.6 (18G1012)

```python
from neo4j import GraphDatabase, basic_auth
driver = GraphDatabase.driver(uri="bolt://127.0.0.1:7687", auth=basic_auth("neo4j", "mypassword"))
```

```
Traceback (most recent call last):
  File "/Volumes/Transcend/work/codes_2020/knowledge_graph_ws/pyenv/lib/python3.5/site-packages/neobolt/direct.py", line 854, in _secure
    s = ssl_context.wrap_socket(s, server_hostname=host if HAS_SNI and host else None)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/ssl.py", line 385, in wrap_socket
    _context=self)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/ssl.py", line 760, in __init__
    self.do_handshake()
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/ssl.py", line 996, in do_handshake
    self._sslobj.do_handshake()
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/ssl.py", line 641, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLError: [SSL: UNKNOWN_PROTOCOL] unknown protocol (_ssl.c:719)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Volumes/Transcend/work/codes_2020/knowledge_graph_ws/run.py", line 11, in <module>
    driver = GraphDatabase.driver(uri="bolt://127.0.0.1:7687", auth=basic_auth("neo4j", "Docare@2018"))
  File "/Volumes/Transcend/work/codes_2020/knowledge_graph_ws/pyenv/lib/python3.5/site-packages/neo4j/__init__.py", line 120, in driver
    return Driver(uri, **config)
  File "/Volumes/Transcend/work/codes_2020/knowledge_graph_ws/pyenv/lib/python3.5/site-packages/neo4j/__init__.py", line 161, in __new__
    return subclass(uri, **config)
  File "/Volumes/Transcend/work/codes_2020/knowledge_graph_ws/pyenv/lib/python3.5/site-packages/neo4j/__init__.py", line 235, in __new__
    pool.release(pool.acquire())
  File "/Volumes/Transcend/work/codes_2020/knowledge_graph_ws/pyenv/lib/python3.5/site-packages/neobolt/direct.py", line 715, in acquire
    return self.acquire_direct(self.address)
  File "/Volumes/Transcend/work/codes_2020/knowledge_graph_ws/pyenv/lib/python3.5/site-packages/neobolt/direct.py", line 608, in acquire_direct
    connection = self.connector(address, error_handler=self.connection_error_handler)
  File "/Volumes/Transcend/work/codes_2020/knowledge_graph_ws/pyenv/lib/python3.5/site-packages/neo4j/__init__.py", line 232, in connector
    return connect(address, **dict(config, **kwargs))
  File "/Volumes/Transcend/work/codes_2020/knowledge_graph_ws/pyenv/lib/python3.5/site-packages/neobolt/direct.py", line 972, in connect
    raise last_error
  File "/Volumes/Transcend/work/codes_2020/knowledge_graph_ws/pyenv/lib/python3.5/site-packages/neobolt/direct.py", line 963, in connect
    s, der_encoded_server_certificate = _secure(s, host, security_plan.ssl_context, **config)
  File "/Volumes/Transcend/work/codes_2020/knowledge_graph_ws/pyenv/lib/python3.5/site-packages/neobolt/direct.py", line 859, in _secure
    raise error
neobolt.exceptions.SecurityError: Failed to establish secure connection to '[SSL: UNKNOWN_PROTOCOL] unknown protocol (_ssl.c:719)'
```

If I run this code and neo4j service on CentOS , It works fine.
however, code on macOS and service on CentOS, the same error

**Comment by martin-neotech** [comment]
@GodsDusk it could be a openssl problem. Try updating the python version 3.5 to the latest. Try with python 3.6 or later to check if those versions work. You could also disable encryption if not in production mode.

https://neo4j.com/docs/operations-manual/3.5/security/ssl-framework/

https://neo4j.com/docs/driver-manual/1.7/client-applications/#driver-configuration-encryption

**Comment by GodsDusk** [comment]
@martin-neotech  I use python3.7 and it works, thanks
