### ISSUE TITLE
cannot authenticate 

### ISSUE THREAD

**Issue by dcsan** [neo4j/neo4j-python-driver#369]
I'm running neo4j via the docker image
I can connect to the DB using the set password from browser and from a docker bash shell.

But the python driver fails to connect with:

> neobolt.exceptions.AuthError: The client is unauthorized due to authentication failure.

```
neo4j==1.7.6
neobolt==1.7.16
neotime==1.7.4
pytz==2019.3
six==1.14.0
```

**Comment by dcsan** [comment]
```python

from neo4j import GraphDatabase

class NeoDriver(object):

    def __init__(self, uri, user, password):
        print('connecting...', user, password)
        self._driver = GraphDatabase.driver(uri, auth=(user, password), encrypted=False)
        print('connected')

def loader():
    print('startup')
    neo = NeoDriver("bolt://0.0.0.0:7687", 'neoj4', 'test')

loader()
```

**Comment by dcsan** [comment]
and full stack trace

```
startup
connecting... neoj4 test
Traceback (most recent call last):
  File "mintest.py", line 31, in <module>
    loader()
  File "mintest.py", line 12, in loader
    neo = NeoDriver("bolt://0.0.0.0:7687", 'neoj4', 'test')
  File "mintest.py", line 7, in __init__
    self._driver = GraphDatabase.driver(uri, auth=(user, password), encrypted=False)
  File "/Users/dcollier/dev/rnd/nlp/scrape-esl/convograph/venv/lib/python3.7/site-packages/neo4j/__init__.py", line 120, in driver
    return Driver(uri, **config)
  File "/Users/dcollier/dev/rnd/nlp/scrape-esl/convograph/venv/lib/python3.7/site-packages/neo4j/__init__.py", line 161, in __new__
    return subclass(uri, **config)
  File "/Users/dcollier/dev/rnd/nlp/scrape-esl/convograph/venv/lib/python3.7/site-packages/neo4j/__init__.py", line 235, in __new__
    pool.release(pool.acquire())
  File "/Users/dcollier/dev/rnd/nlp/scrape-esl/convograph/venv/lib/python3.7/site-packages/neobolt/direct.py", line 715, in acquire
    return self.acquire_direct(self.address)
  File "/Users/dcollier/dev/rnd/nlp/scrape-esl/convograph/venv/lib/python3.7/site-packages/neobolt/direct.py", line 608, in acquire_direct
    connection = self.connector(address, error_handler=self.connection_error_handler)
  File "/Users/dcollier/dev/rnd/nlp/scrape-esl/convograph/venv/lib/python3.7/site-packages/neo4j/__init__.py", line 232, in connector
    return connect(address, **dict(config, **kwargs))
  File "/Users/dcollier/dev/rnd/nlp/scrape-esl/convograph/venv/lib/python3.7/site-packages/neobolt/direct.py", line 972, in connect
    raise last_error
  File "/Users/dcollier/dev/rnd/nlp/scrape-esl/convograph/venv/lib/python3.7/site-packages/neobolt/direct.py", line 964, in connect
    connection = _handshake(s, address, der_encoded_server_certificate, **config)
  File "/Users/dcollier/dev/rnd/nlp/scrape-esl/convograph/venv/lib/python3.7/site-packages/neobolt/direct.py", line 932, in _handshake
    connection.hello()
  File "/Users/dcollier/dev/rnd/nlp/scrape-esl/convograph/venv/lib/python3.7/site-packages/neobolt/direct.py", line 249, in hello
    self.sync()
  File "/Users/dcollier/dev/rnd/nlp/scrape-esl/convograph/venv/lib/python3.7/site-packages/neobolt/direct.py", line 527, in sync
    detail_delta, summary_delta = self.fetch()
  File "/Users/dcollier/dev/rnd/nlp/scrape-esl/convograph/venv/lib/python3.7/site-packages/neobolt/direct.py", line 419, in fetch
    return self._fetch()
  File "/Users/dcollier/dev/rnd/nlp/scrape-esl/convograph/venv/lib/python3.7/site-packages/neobolt/direct.py", line 461, in _fetch
    response.on_failure(summary_metadata or {})
  File "/Users/dcollier/dev/rnd/nlp/scrape-esl/convograph/venv/lib/python3.7/site-packages/neobolt/direct.py", line 774, in on_failure
    raise AuthError(message)
neobolt.exceptions.AuthError: The client is unauthorized due to authentication failure.
```

**Comment by dcsan** [comment]
FWIW this is the docker config:

```
docker run --rm \
    --name neodocker \
    -p7474:7474 -p7687:7687 \
    --env NEO4J_AUTH=neo4j/test \
    --user="neo4j" \
    neo4j:latest
```

**Comment by dcsan** [comment]
also logged on the docker repo
https://github.com/neo4j/docker-neo4j/issues/238

but since I can login via web UI and bash on docker:
```
docker exec -it neodocker bash

neo4j@b384ab88c879:~$ cypher-shell -u neo4j -p test
Connected to Neo4j 4.0.1 at neo4j://localhost:7687 as user neo4j.

```
I think it's the python driver thats borked.

**Comment by dcsan** [comment]
update: tried using a plain system install of neo4j with exactly the same problems
I even ran the 

```
./neo4j-admin set-initial-password test
```

and restarted the server. same, cannot login to neo4j 

also tried different protocols:

```
bolt://localhost:7687
neo4j://localhost:7687
bolt://0.0.0.0:7687
neo4j://0.0.0.0:7687
```

nothing works.

btw I also had to install a custom version of the JVM to even get this to work.

```
▶ java -version
openjdk version "11.0.6" 2020-01-14
OpenJDK Runtime Environment AdoptOpenJDK (build 11.0.6+10)
OpenJDK 64-Bit Server VM AdoptOpenJDK (build 11.0.6+10, mixed mode)
```

**Comment by dcsan** [comment]
neoj4 is not neo4j !!
