### ISSUE TITLE
Cannot use python bolt with neo4 docker image

### ISSUE THREAD

**Issue by contra-bit** [neo4j/neo4j-python-driver#372]
### Cannot connect to Database

- Neo4j version: Community 4.0.1
- Neo4j Mode: Single instance using Docker
- Driver version: neobolt-1.7.16
- Operating system: Arch Linux: 5.5.9-arch1-2
- **Steps to reproduce**

Setup for python (see https://neo4j.com/developer/python/)
``` bash
pipenv install neo4j
pipenv shell
```
 Minimal Setup for testing Neo4j, the password has been replaced with password
``` python
from neo4j import GraphDatabase

driver = GraphDatabase.driver("bolt://localhost:7687", auth=("neo4j", "password"))

def add_friend(tx, name, friend_name):
    tx.run("MERGE (a:Person {name: $name}) "
           "MERGE (a)-[:KNOWS]->(friend:Person {name: $friend_name})",
           name=name, friend_name=friend_name)

def print_friends(tx, name):
    for record in tx.run("MATCH (a:Person)-[:KNOWS]->(friend) WHERE a.name = $name "
                         "RETURN friend.name ORDER BY friend.name", name=name):
        print(record["friend.name"])

with driver.session() as session:
    session.write_transaction(add_friend, "Arthur", "Guinevere")
    session.write_transaction(add_friend, "Arthur", "Lancelot")
    session.write_transaction(add_friend, "Arthur", "Merlin")
    session.read_transaction(print_friends, "Arthur")

driver.close()
```
Docker was setup in the way the dockhub tutorial says:
``` bash
docker run \                                                                                                         ✘ 130 
    --publish=7474:7474 --publish=7687:7687 \
    --volume=$HOME/Code/Learn/neo4j/data:/data \
    neo4j
```

The default password was changed.
Neo4J Browser outputs 

You are connected as user neo4j
to neo4j://0.0.0.0:7687

After I have connected to the database i import the movie data with 
```
:play movies
```

Example Movie Queries are now possible
### Expected behavior
Neo4j writes the Transaction when example.py is executed, thus the second query is run successfully

- Actual behavior
To test the python driver we import example.py in the interpreter and get this Stacktrace
``` python
>>> import example
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/s0/Code/Learn/neo4jdriver/example.py", line 3, in <module>
    driver = GraphDatabase.driver("bolt://localhost:7687", auth=("neo4j", "password"))
  File "/home/s0/.local/lib/python3.8/site-packages/neo4j/__init__.py", line 120, in driver
    return Driver(uri, **config)
  File "/home/s0/.local/lib/python3.8/site-packages/neo4j/__init__.py", line 161, in __new__
    return subclass(uri, **config)
  File "/home/s0/.local/lib/python3.8/site-packages/neo4j/__init__.py", line 235, in __new__
    pool.release(pool.acquire())
  File "/home/s0/.local/lib/python3.8/site-packages/neobolt/direct.py", line 715, in acquire
    return self.acquire_direct(self.address)
  File "/home/s0/.local/lib/python3.8/site-packages/neobolt/direct.py", line 608, in acquire_direct
    connection = self.connector(address, error_handler=self.connection_error_handler)
  File "/home/s0/.local/lib/python3.8/site-packages/neo4j/__init__.py", line 232, in connector
    return connect(address, **dict(config, **kwargs))
  File "/home/s0/.local/lib/python3.8/site-packages/neobolt/direct.py", line 972, in connect
    raise last_error
  File "/home/s0/.local/lib/python3.8/site-packages/neobolt/direct.py", line 963, in connect
    s, der_encoded_server_certificate = _secure(s, host, security_plan.ssl_context, **config)
  File "/home/s0/.local/lib/python3.8/site-packages/neobolt/direct.py", line 854, in _secure
    s = ssl_context.wrap_socket(s, server_hostname=host if HAS_SNI and host else None)
  File "/usr/lib/python3.8/ssl.py", line 500, in wrap_socket
    return self.sslsocket_class._create(
  File "/usr/lib/python3.8/ssl.py", line 1040, in _create
    self.do_handshake()
  File "/usr/lib/python3.8/ssl.py", line 1309, in do_handshake
    self._sslobj.do_handshake()
OSError: [Errno 0] Error
>>> 
```

I guess this error has do with a deprecation of tls. Could it be possible, that neobolt uses a outdated driver?

What can I do to fix this
Thank you a lot and stay healthy

**Comment by KevinvOosterhout** [comment]
This is due to Neo4j 4.x not creating self signed certificates by default. You need to either disable encryption on the client side or go the recommended route and generate certificates and install them in Neo4j. Take a look at https://github.com/FiloSottile/mkcert A really easy solution to generate the certificates in the correct format

**Comment by martin-neotech** [comment]
@KevinvOosterhout thanks for your reply.

Sollution for testenvironment:

`driver = GraphDatabase.driver("bolt://localhost:7687", auth=("neo4j", "password"), encrypted=False)`
