### ISSUE TITLE
This driver doesn't work with the launched Docker container (with :latest).

### ISSUE THREAD

**Issue by alxfed** [neo4j/neo4j-python-driver#382]
I'm not sure whether it is your driver or the image of the :latest Docker container, but, when I launch the container (with _all_ available ports: 7474, 7473, 7678 mapped to the corresponding host ports) here's what I get in the PyCharm debugger, in the module `direct.py` in definition of _secure:
<pre>
Connected to pydev debugger (build 193.6911.25)
Traceback (most recent call last):
  File "/.../miniconda3/envs/jupy/lib/python3.8/site-packages/neobolt/direct.py", line 854, in _secure
    s = ssl_context.wrap_socket(s, server_hostname=host if HAS_SNI and host else None)
  File "/.../miniconda3/envs/jupy/lib/python3.8/ssl.py", line 500, in wrap_socket
    return self.sslsocket_class._create(
  File "/.../miniconda3/envs/jupy/lib/python3.8/ssl.py", line 1040, in _create
    self.do_handshake()
  File "/.../miniconda3/envs/jupy/lib/python3.8/ssl.py", line 1309, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLError: [SSL: KRB5_S_TKT_NYV] unexpected eof while reading (_ssl.c:1108)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/.../miniconda3/envs/jupy/lib/python3.8/site-packages/neobolt/direct.py", line 608, in acquire_direct
    connection = self.connector(address, error_handler=self.connection_error_handler)
  File "/.../miniconda3/envs/jupy/lib/python3.8/site-packages/neo4j/__init__.py", line 232, in connector
    return connect(address, **dict(config, **kwargs))
  File "/.../miniconda3/envs/jupy/lib/python3.8/site-packages/neobolt/direct.py", line 972, in connect
    raise last_error
  File "/.../miniconda3/envs/jupy/lib/python3.8/site-packages/neobolt/direct.py", line 963, in connect
    s, der_encoded_server_certificate = _secure(s, host, security_plan.ssl_context, **config)
  File "/.../miniconda3/envs/jupy/lib/python3.8/site-packages/neobolt/direct.py", line 859, in _secure
    raise error
neobolt.exceptions.SecurityError: Failed to establish secure connection to '[SSL: KRB5_S_TKT_NYV] unexpected eof while reading (_ssl.c:1108)'

Process finished with exit code 130 (interrupted by signal 2: SIGINT)
</pre>

Any idea why your driver (or your image) is failing to establish a (totally __useless__) SSL connection?

By the way, when I'm launching the container it shows the interface on http (not on https) too:

<pre>
Changed password for user 'neo4j'.
Directories in use:
  home:         /var/lib/neo4j
  config:       /var/lib/neo4j/conf
  logs:         /logs
  plugins:      /plugins
  import:       /var/lib/neo4j/import
  data:         /var/lib/neo4j/data
  certificates: /var/lib/neo4j/certificates
  run:          /var/lib/neo4j/run
Starting Neo4j.
2020-03-30 17:02:11.213+0000 INFO  ======== Neo4j 4.0.2 ========
2020-03-30 17:02:11.219+0000 INFO  Starting...
2020-03-30 17:02:13.671+0000 INFO  Bolt enabled on 0.0.0.0:7687.
2020-03-30 17:02:13.671+0000 INFO  Started.
2020-03-30 17:02:14.516+0000 INFO  Remote interface available at http://0.0.0.0:7474/
</pre>

And to be absolutely precise, the docker command is:
<pre>
docker run -p 7473:7473 -p 7474:7474 -p 7687:7687 -v /.../neo4j/data:/data -v /.../neo4j/logs:/logs -v /.../neo4j/plugins:/plugins --env NEO4J_AUTH=neo4j/password --name neodb -d neo4j:latest 
</pre>

**Comment by jholtom-ciena** [comment]
I'm going to assume you're using neo4j==1.7, in which case try adding encrypted=False to your driver-conection - eg:
```driver = GraphDatabase.driver('bolt://localhost:7687', encrypted=False, auth=basic_auth('neo4j','test'))```

**Comment by alxfed** [comment]
`1.7.6` and YES, of course that worked. Thank you.

And, see? I'm not asking the stupid question: "why make a container open interface in browser for log in without ssl but driver with a default encryption?". That's the matter of personal consciousness.

Once again, thank you so very much for the prompt response with an invaluable piece of useful advice.

**Comment by jholtom-ciena** [comment]
I should have added, that your docker image is running the latest v4 Neo4j database, and that's where your disconnect lies - if you use the 1.7 driver with a v3.5 database it all works together nicely. To access the new features of the v4 database, an updated (v4) driver will be needed - but this has not been released yet.

**Comment by alxfed** [comment]
Yep, I've already got it. Thank you. Once you've mentioned `1.7` I started looking at versions of everything. :)
