### ISSUE TITLE
NotALeaderError in read session

### ISSUE THREAD

**Issue by aonamrata** [neo4j/neo4j-python-driver#429]
**Error:**
neobolt.exceptions.NotALeaderError
neobolt.exceptions.NotALeaderError: Should only attempt to take locks when leader.

- Neo4j version: 3.5.18
- Neo4j Mode: Casual cluster 
- Driver version: Python 1.7.6 with Python 3.6 + Flask
- Operating system: Windows

- **Steps to reproduce**

- Expected behavior

- Actual behavior

code:
```
 with neo4j_driver.session(access_mode='READ') as session:
        count_query= f"""MATCH (i:Identity)-[:HAS_PROFILE]->(p:Profile)-[k:HAS_ACCESS_TO]->(r)
            .....
        """
        result = session.run(
            count_query, identity_id=identity_id, profile_type=profile_type)
        count_result = result.single()
```

It is similar to https://github.com/neo4j/neo4j-python-driver/issues/276 so I tried adding 
```
from neobolt.diagnostics import watch
watch("neobolt")
```

and these are the logs 
```
$ python dev.py
←[36m2020-06-19 15:11:30,144  Attempting to update routing table from Address(host='dev-neo4j-cluster.xxxxxx', port=7687)←[0m
←[36m2020-06-19 15:11:30,191  [#0000]  C: <RESOLVE> Address(host='dev-neo4j-cluster.dev.theorchard.io', p
ort=7687)←[0m
←[36m2020-06-19 15:11:30,519  [#0000]  C: <OPEN> ('10.101.2.172', 7687)←[0m
←[36m2020-06-19 15:11:31,210  [#C161]  C: <SECURE> dev-neo4j-cluster.dev.theorchard.io←[0m
←[36m2020-06-19 15:11:31,652  [#C161]  C: <MAGIC> 0x6060B017←[0m
←[36m2020-06-19 15:11:31,653  [#C161]  C: <HANDSHAKE> 0x00000003 0x00000002 0x00000001 0x00000000←[0m
←[36m2020-06-19 15:11:31,868  [#C161]  S: <HANDSHAKE> 0x00000003←[0m
←[36m2020-06-19 15:11:31,872  [#C161]  C: HELLO {'user_agent': 'neobolt/1.7.17 Python/3.6.0-final-0 (win3
2)', 'scheme': 'basic', 'principal': 'npatel', 'credentials': '*******'}←[0m
←[36m2020-06-19 15:11:32,087  [#C161]  S: SUCCESS {'server': 'Neo4j/3.5.18', 'connection_id': 'bolt-20955
'}←[0m
←[36m2020-06-19 15:11:32,089  [#C161]  C: RUN 'CALL dbms.cluster.routing.getRoutingTable($context)' {'con
text': {}} {}←[0m
←[36m2020-06-19 15:11:32,090  [#C161]  C: PULL_ALL←[0m
←[36m2020-06-19 15:11:32,310  [#C161]  S: SUCCESS {'t_first': 1, 'fields': ['ttl', 'servers']}←[0m
←[36m2020-06-19 15:11:32,312  [#C161]  S: RECORD * 1←[0m
←[36m2020-06-19 15:11:32,312  [#C161]  S: SUCCESS {'bookmark': 'neo4j:bookmark:v1:tx12328175', 'type': 'r
', 't_last': 0}←[0m
←[36m2020-06-19 15:11:32,314  [#C161]  C: GOODBYE←[0m
←[36m2020-06-19 15:11:32,315  [#C161]  C: <CLOSE>←[0m
←[36m2020-06-19 15:11:32,317  Successfully updated routing table from Address(host='dev-neo4j-cluster.xxxxxx', port=7687) (<neobolt.routing.RoutingTable object at 0x0000002095E415F8>)←[0m
 * Serving Flask app "ows-permissions" (lazy loading)
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: on
 * Restarting with stat
←[36m2020-06-19 15:11:34,012  Attempting to update routing table from Address(host='dev-neo4j-cluster.xxxxxx', port=7687)←[0m
←[36m2020-06-19 15:11:34,013  [#0000]  C: <RESOLVE> Address(host='dev-neo4j-cluster.dev.theorchard.io', p
ort=7687)←[0m
←[36m2020-06-19 15:11:34,017  [#0000]  C: <OPEN> ('10.101.2.172', 7687)←[0m
←[36m2020-06-19 15:11:34,231  [#C165]  C: <SECURE> dev-neo4j-cluster.dev.theorchard.io←[0m
←[36m2020-06-19 15:11:34,684  [#C165]  C: <MAGIC> 0x6060B017←[0m
←[36m2020-06-19 15:11:34,685  [#C165]  C: <HANDSHAKE> 0x00000003 0x00000002 0x00000001 0x00000000←[0m
←[36m2020-06-19 15:11:34,898  [#C165]  S: <HANDSHAKE> 0x00000003←[0m
←[36m2020-06-19 15:11:34,900  [#C165]  C: HELLO {'user_agent': 'neobolt/1.7.17 Python/3.6.0-final-0 (win3
2)', 'scheme': 'basic', 'principal': 'npatel', 'credentials': '*******'}←[0m
←[36m2020-06-19 15:11:35,115  [#C165]  S: SUCCESS {'server': 'Neo4j/3.5.18', 'connection_id': 'bolt-20956
'}←[0m
←[36m2020-06-19 15:11:35,117  [#C165]  C: RUN 'CALL dbms.cluster.routing.getRoutingTable($context)' {'con
text': {}} {}←[0m
←[36m2020-06-19 15:11:35,119  [#C165]  C: PULL_ALL←[0m
←[36m2020-06-19 15:11:35,336  [#C165]  S: SUCCESS {'t_first': 1, 'fields': ['ttl', 'servers']}←[0m
←[36m2020-06-19 15:11:35,337  [#C165]  S: RECORD * 1←[0m
←[36m2020-06-19 15:11:35,337  [#C165]  S: SUCCESS {'bookmark': 'neo4j:bookmark:v1:tx12328175', 'type': 'r
', 't_last': 0}←[0m
←[36m2020-06-19 15:11:35,340  [#C165]  C: GOODBYE←[0m
←[36m2020-06-19 15:11:35,342  [#C165]  C: <CLOSE>←[0m
←[36m2020-06-19 15:11:35,345  Successfully updated routing table from Address(host='dev-neo4j-cluster.xxxxxx', port=7687) (<neobolt.routing.RoutingTable object at 0x0000002696F01518>)←[0m
 * Debugger is active!
 * Debugger PIN: 212-272-298
 * Running on http://0.0.0.0:5002/ (Press CTRL+C to quit)
←[36m2020-06-19 15:11:43,560  [#0000]  C: <RESOLVE> Address(host='dev-neo4j-cluster-i-0bffa73bb6e73446a.xxxxxx', port=7687)←[0m
←[36m2020-06-19 15:11:43,561  [#0000]  C: <OPEN> ('10.101.7.21', 7687)←[0m
←[36m2020-06-19 15:11:43,891  [#C169]  C: <SECURE> dev-neo4j-cluster-i-0bffa73bb6e73446a.xxxxxx←[0m
←[36m2020-06-19 15:11:44,324  [#C169]  C: <MAGIC> 0x6060B017←[0m
←[36m2020-06-19 15:11:44,325  [#C169]  C: <HANDSHAKE> 0x00000003 0x00000002 0x00000001 0x00000000←[0m
←[36m2020-06-19 15:11:44,539  [#C169]  S: <HANDSHAKE> 0x00000003←[0m
←[36m2020-06-19 15:11:44,543  [#C169]  C: HELLO {'user_agent': 'neobolt/1.7.17 Python/3.6.0-final-0 (win3
2)', 'scheme': 'basic', 'principal': 'npatel', 'credentials': '*******'}←[0m
←[36m2020-06-19 15:11:44,759  [#C169]  S: SUCCESS {'server': 'Neo4j/3.5.18', 'connection_id': 'bolt-5314'
}←[0m
←[36m2020-06-19 15:11:44,888  [#C169]  C: RUN 'MATCH (i:Identity)-[:HAS_PROFILE]->(x) RETURN count(x) as total\n        ' {} {}←[0m
←[36m2020-06-19 15:11:44,890  [#C169]  C: PULL_ALL←[0m
←[36m2020-06-19 15:11:45,110  [#C169]  S: FAILURE {'code': 'Neo.ClientError.Cluster.NotALeader', 'message
': 'Should only attempt to take locks when leader.'}←[0m
←[36m2020-06-19 15:11:45,110  [#C169]  C: RESET←[0m
←[36m2020-06-19 15:11:45,111  [#C169]  S: IGNORED←[0m
←[36m2020-06-19 15:11:45,374  [#C169]  S: SUCCESS {}←[0m
127.0.0.1 - - [19/Jun/2020 15:11:45] "GET /identity/resources/LabelParticipant?role=administrator&profile
_type=InsightsProfile HTTP/1.1" 500 -
Traceback (most recent call last):
  File "D:\orchardws\ows-permissions\env\lib\site-packages\flask\app.py", line 2463, in __call__
    return self.wsgi_app(environ, start_response)
.....
  File "D:\orchardws\ows-permissions\permissions\models\resource.py", line 107, in get_role_resources
    count_query, identity_id=identity_id, profile_type=profile_type)
  File "D:\orchardws\ows-permissions\env\lib\site-packages\neo4j\__init__.py", line 503, in run
    self._connection.fetch()
  File "D:\orchardws\ows-permissions\env\lib\site-packages\neobolt\direct.py", line 422, in fetch
    raise error
  File "D:\orchardws\ows-permissions\env\lib\site-packages\neobolt\direct.py", line 419, in fetch
    return self._fetch()
  File "D:\orchardws\ows-permissions\env\lib\site-packages\neobolt\direct.py", line 461, in _fetch
    response.on_failure(summary_metadata or {})
  File "D:\orchardws\ows-permissions\env\lib\site-packages\neobolt\direct.py", line 755, in on_failure
    raise CypherError.hydrate(**metadata)
neobolt.exceptions.NotALeaderError: Should only attempt to take locks when leader.

```

**Comment by technige** [comment]
A `NotALeader` error is an expected error when a write operation is sent to a read-only cluster member. It looks like you are using `session.run`, which will not automatically retry against a different member. I suggest using transaction functions instead.

https://neo4j.com/docs/driver-manual/current/session-api/simple/#driver-simple-transaction-fn

**Comment by aonamrata** [comment]
We are not on 4.0 driver so the syntax does not work as it is. Let me try the 1.7x version documentation. 

This is my query 
```
MATCH (i:Identity)-[:HAS_PROFILE]->(p:Profile)-[k:HAS_ACCESS_TO]->(r)
            WHERE
                i.id = $identity_id AND
                p.profileType = $profile_type AND
                "admin" in p.roles
            WITH r
            CALL apoc.do.when(
                r.id = '*',
                'MATCH (x:Artist) return x',
                'MATCH (r)-[*0..1]->(x:Artists) return x',
                {{ r:r }}
            ) YIELD value
            WITH value.x as x
```
Which is technically a READ query. Does it try to take lock due to APOC functions?

**Comment by martin-neotech** [comment]
@aonamrata yes that looks like a read please raise this issue on https://github.com/neo4j/neo4j/issues to ask about APOC functions.

The documentation for 1.7

https://neo4j.com/docs/driver-manual/1.7/sessions-transactions/#driver-transactions-access-mode

https://neo4j.com/docs/driver-manual/1.7/sessions-transactions/#driver-transactions-transaction-functions
