### ISSUE TITLE
Cannot start Django with neo4j driver in version 4.0.x. On 1.7.0 works.

### ISSUE THREAD

**Issue by pitniecik** [neo4j/neo4j-python-driver#453]
Cannot start Django with neo4j driver in version 4.0.x. On 1.7.0 works.

**Driver version**: Python driver 4.0.x  
**Operating System:** Docker, Django-3.0.8, Python 3.7, Neomodel 3.2.9

### Steps to reproduce
1. python manage.py runserver
### Expected behavior
Start Django server
### Actual behavior
[0m[91mTraceback (most recent call last):
  File "manage.py", line 15, in <module>
[0m[91m    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python3.7/site-packages/django/core/management/__init__.py", line 401, in execute_from_command_line
[0m[91m    utility.execute()
  File "/usr/local/lib/python3.7/site-packages/django/core/management/__init__.py", line 395, in execute
[0m[91m    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python3.7/site-packages/django/core/management/base.py", line 341, in run_from_argv
[0m[91m    connections.close_all()
  File "/usr/local/lib/python3.7/site-packages/django/db/utils.py", line 225, in close_all
[0m[91m    for alias in self:
  File "/usr/local/lib/python3.7/site-packages/django/db/utils.py", line 219, in __iter__
[0m[91m    return iter(self.databases)
  File "/usr/local/lib/python3.7/site-packages/django/utils/functional.py", line 48, in __get__
[0m[91m    res = instance.__dict__[self.name] = self.func(instance)
  File "/usr/local/lib/python3.7/site-packages/django/db/utils.py", line 153, in databases
[0m[91m    self._databases = settings.DATABASES
  File "/usr/local/lib/python3.7/site-packages/django/conf/__init__.py", line 76, in __getattr__
[0m[91m    self._setup(name)
  File "/usr/local/lib/python3.7/site-packages/django/conf/__init__.py", line 63, in _setup
[0m[91m    self._wrapped = Settings(settings_module)
  File "/usr/local/lib/python3.7/site-packages/django/conf/__init__.py", line 142, in __init__
[0m[91m    mod = importlib.import_module(self.SETTINGS_MODULE)
  File "/usr/local/lib/python3.7/importlib/__init__.py", line 127, in import_module
[0m[91m    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
[0m[91m  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
[0m[91m  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
[0m[91m  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
[0m[91m  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/gp_pdf/gp_pdf_backend/settings.py", line 14, in <module>
[0m[91m    from neomodel import config
  File "/usr/local/lib/python3.7/site-packages/neomodel/__init__.py", line 3, in <module>
[0m[91m    from .core import *
  File "/usr/local/lib/python3.7/site-packages/neomodel/core.py", line 9, in <module>
[0m[91m    from neomodel.util import Database, classproperty, _UnsavedNode, _get_node_properties
  File "/usr/local/lib/python3.7/site-packages/neomodel/util.py", line 8, in <module>
[0m[91m    from neo4j.v1 import GraphDatabase, basic_auth, CypherError, SessionError
  File "/usr/local/lib/python3.7/site-packages/neo4j/__init__.py", line 93, in <module>
[0m[91m    from neo4j.data import (
  File "/usr/local/lib/python3.7/site-packages/neo4j/data.py", line 30, in <module>
[0m[91m    from neo4j.packstream import INT64_MIN, INT64_MAX, Structure
ImportError: cannot import name 'INT64_MIN' from 'neo4j.packstream' (/usr/local/lib/python3.7/site-packages/neo4j/packstream/__init__.py)

**Comment by KevinvOosterhout** [comment]
This is probably due to neomodel not updating yet to the 4.x drivers. Neomodel is made for the 1.7 drivers. You might want to post it over there.

**Comment by martin-neotech** [comment]
https://github.com/neo4j-contrib/neomodel/issues/485
