### ISSUE TITLE
ValueError: URI scheme 'neo4j' not supported

### ISSUE THREAD

**Issue by DrMartiner** [neo4j/neo4j-python-driver#454]
**Neo4j Version:** 4.1-enterprise
**Neo4j Mode**: Single instance  
**Driver version**: Python driver 3.8
**Lib version**: ^4.0.2

```python
from neo4j import GraphDatabase, Driver
from application import config

driver = GraphDatabase.driver("neo4j://neo4j:7687", auth=("neo4j", "changeme"))
```

Exception:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.8/site-packages/neo4j/__init__.py", line 108, in driver
    return Driver(uri, **config)
  File "/usr/local/lib/python3.8/site-packages/neo4j/__init__.py", line 148, in __new__
    raise ValueError("URI scheme %r not supported" % parsed.scheme)
ValueError: URI scheme 'neo4j' not supported```

UPD: the problem was solved via downgrade to 4.0.1

**Comment by martin-neotech** [comment]
@DrMartiner Hi, the parsing of the `"neo4j://neo4j:7687"` works fine. The 4.0.x driver throws `ConfigurationError` for unsupported uri scheme.

example using `"xxneo4j://neo4j:7687"`

```
raise ConfigurationError("URI scheme {!r} is not supported. Supported URI schemes are {}. Examples: bolt://host[:port] or neo4j://host[:port][?routing_context]".format(
neo4j.exceptions.ConfigurationError: URI scheme 'xxneo4j' is not supported. Supported URI schemes are ['bolt', 'bolt+ssc', 'bolt+s', 'neo4j', 'neo4j+ssc', 'neo4j+s']. Examples: bolt://host[:port] or neo4j://host[:port][?routing_context]
```

Next time check your version that you are using with:

```
python -m pip freeze
```

thanks
