### ISSUE TITLE
Error connecting to neo4j database from docker

### ISSUE THREAD

**Issue by jramacha** [neo4j/neo4j-python-driver#474]
Neo4j version: Version:	4.1.3
Edition:	Community
Name:	neo4j
Databases:	 :dbs
Information:	 :sysinfo
Query List:	 :queries

Driver version: neo4j (4.1.0)
neo4j-driver (4.1.1)

Operating system:
root@49ca83462ad0:/app# uname -a    
Linux 49ca83462ad0 5.4.39-linuxkit #1 SMP Fri May 8 23:03:06 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
inside Docker

Steps to reproduce
Run connect using example from README.md from a Django endpoint.
but I get an error 

```

neo4j:7687
****************************************************************************************************
Internal Server Error: /trips/
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/neo4j/addressing.py", line 113, in _dns_resolve
    info = getaddrinfo(address.host, address.port, family, SOCK_STREAM)
  File "/usr/lib/python3.7/socket.py", line 748, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -2] Name or service not known
...
ndling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.7/dist-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python3.7/dist-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python3.7/dist-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/django/views/generic/base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/rest_framework/views.py", line 505, in dispatch
    response = self.handle_exception(exc)
  File "/usr/local/lib/python3.7/dist-packages/rest_framework/views.py", line 465, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/usr/local/lib/python3.7/dist-packages/rest_framework/views.py", line 476, in raise_uncaught_exception
    raise exc
  File "/usr/local/lib/python3.7/dist-packages/rest_framework/views.py", line 502, in dispatch
    response = handler(request, *args, **kwargs)
  File "/app/trips/views.py", line 83, in get
    neoUser = NeoUser.nodes.get_or_none(userId=request.user.id)
  File "/usr/local/lib/python3.7/dist-packages/neomodel/match.py", line 619, in get_or_none
    return self.get(**kwargs)
  File "/usr/local/lib/python3.7/dist-packages/neomodel/match.py", line 603, in get
    result = self._get(limit=2, lazy=lazy, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/neomodel/match.py", line 594, in _get
    return self.query_cls(self).build_ast()._execute(lazy)
  File "/usr/local/lib/python3.7/dist-packages/neomodel/match.py", line 499, in _execute
    results, _ = db.cypher_query(query, self._query_params, resolve_objects=True)
  File "/usr/local/lib/python3.7/dist-packages/neomodel/util.py", line 34, in wrapper
    _db.set_connection(config.DATABASE_URL)
  File "/usr/local/lib/python3.7/dist-packages/neomodel/util.py", line 102, in set_connection
    max_connection_pool_size=config.MAX_CONNECTION_POOL_SIZE)
  File "/usr/local/lib/python3.7/dist-packages/neo4j/__init__.py", line 183, in driver
    return cls.bolt_driver(parsed.netloc, auth=auth, **config)
  File "/usr/local/lib/python3.7/dist-packages/neo4j/__init__.py", line 196, in bolt_driver
    return BoltDriver.open(target, auth=auth, **config)
  File "/usr/local/lib/python3.7/dist-packages/neo4j/__init__.py", line 359, in open
    pool = BoltPool.open(address, auth=auth, pool_config=pool_config, workspace_config=default_workspace_config)
  File "/usr/local/lib/python3.7/dist-packages/neo4j/io/__init__.py", line 531, in open
    seeds = [pool.acquire() for _ in range(pool_config.init_size)]
  File "/usr/local/lib/python3.7/dist-packages/neo4j/io/__init__.py", line 531, in <listcomp>
    seeds = [pool.acquire() for _ in range(pool_config.init_size)]
  File "/usr/local/lib/python3.7/dist-packages/neo4j/io/__init__.py", line 545, in acquire
    return self._acquire(self.address, timeout)
  File "/usr/local/lib/python3.7/dist-packages/neo4j/io/__init__.py", line 409, in _acquire
    connection = self.opener(address, timeout)
  File "/usr/local/lib/python3.7/dist-packages/neo4j/io/__init__.py", line 528, in opener
    return Bolt.open(addr, auth=auth, timeout=timeout, routing_context=routing_context, **pool_config)
  File "/usr/local/lib/python3.7/dist-packages/neo4j/io/__init__.py", line 198, in open
    keep_alive=pool_config.keep_alive,
  File "/usr/local/lib/python3.7/dist-packages/neo4j/io/__init__.py", line 1035, in connect
    for resolved_address in Address(address).resolve(resolver=custom_resolver):
  File "/usr/local/lib/python3.7/dist-packages/neo4j/addressing.py", line 149, in resolve
    resolved.extend(self._dns_resolve(self, family))
  File "/usr/local/lib/python3.7/dist-packages/neo4j/addressing.py", line 115, in _dns_resolve
    raise ValueError("Cannot resolve address {}".format(address))
ValueError: Cannot resolve address neo4j:7687
```

I can acess http://localhost:7474/browser/ on my mac, also

`jramachandran@home-air % curl localhost:7474
{
  "bolt_routing" : "neo4j://localhost:7687",
  "transaction" : "http://localhost:7474/db/{databaseName}/tx",
  "bolt_direct" : "bolt://localhost:7687",
  "neo4j_version" : "4.1.3",
  "neo4j_edition" : "community"
}%    `

**Comment by 2hdddg** [comment]
Looks like you are connecting to neo4j:7687, should be neo4j://localhost:7687, also make sure that port 7687 is mapped to your host port when starting the docker instance (port 7474 is open since http API is working).

**Comment by zacharymostowsky** [comment]
Hi @2hdddg I was helping @jramacha troubleshoot this yesterday. For more context, we are using neomodel to connect our django api to neo4j. This api is also containerized. Both the API and neo4j containers run with docker-compose. This works great on most machines but not the OPs. Printing the host right before the neo4j query shows the correct value (neo4j://graph_db:7687) where graph_db is the name of the neo4j container.

**Comment by jramacha** [comment]
Thanks @zacharymostowsky  and @2hdddg I am also able to ping  and send curl 7474 to the graph_db(neo4j) container from our app container.
```
jramachandran@home-air stack-orchestrator % docker exec -it app bash
root@49ca83462ad0:/app# ping graph_db
PING graph_db (172.18.0.2) 56(84) bytes of data.
64 bytes from graph_db.stack-orchestrator_default (172.18.0.2): icmp_seq=1 ttl=64 time=0.573 ms
64 bytes from graph_db.stack-orchestrator_default (172.18.0.2): icmp_seq=2 ttl=64 time=0.210 ms
64 bytes from graph_db.stack-orchestrator_default (172.18.0.2): icmp_seq=3 ttl=64 time=0.209 ms
^C
--- graph_db ping statistics ---
3 packets transmitted, 3 received, 0% packet loss, time 2010ms
rtt min/avg/max/mdev = 0.209/0.330/0.573/0.172 ms
root@49ca83462ad0:/app# curl graph_db:7687
not a WebSocket handshake request: missing upgraderoot@49ca83462ad0:/app# 
root@49ca83462ad0:/app# 
root@49ca83462ad0:/app# curl graph_db:7474
{
  "bolt_routing" : "neo4j://null:7687",
  "transaction" : "http://graph_db:7474/db/{databaseName}/tx",
  "bolt_direct" : "bolt://null:7687",
  "neo4j_version" : "4.1.3",
  "neo4j_edition" : "community"
}root@49ca83462ad0:/app# 

```

**Comment by jramacha** [comment]
Thanks guys think I got it working.

**Comment by Zeyad-Mahmoud-1** [comment]
@jramacha can you let me know how did you solve it
