### ISSUE TITLE
ModuleNotFoundError: No module named 'neo4j.bolt'

### ISSUE THREAD

**Issue by blshkv** [neo4j/neo4j-python-driver#482]
```
bash$ pybolt 
Traceback (most recent call last):
  File "/usr/lib/python-exec/python3.7/pybolt", line 33, in <module>
    sys.exit(load_entry_point('neo4j==4.2.0', 'console_scripts', 'pybolt')())
  File "/usr/lib/python3.7/site-packages/pkg_resources/__init__.py", line 473, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2843, in load_entry_point
    return ep.load()
  File "/usr/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2447, in load
    return self.resolve()
  File "/usr/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2453, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
ModuleNotFoundError: No module named 'neo4j.bolt'
```
dev-db/neo4j-community-4.0.4
dev-python/neo4j-4.2.0
**Operating System:** Pentoo/Gentoo

### Steps to reproduce
```
python3.7 setup.py build -j 4
running build
running build_py
creating /var/tmp/portage/dev-python/neo4j-4.2.0/work/neo4j-4.2.0-python3_7/lib/neo4j
copying neo4j/routing.py -> /var/tmp/portage/dev-python/neo4j-4.2.0/work/neo4j-4.2.0-python3_7/lib/neo4j
copying neo4j/packstream.py -> /var/tmp/portage/dev-python/neo4j-4.2.0/work/neo4j-4.2.0-python3_7/lib/neo4j
copying neo4j/meta.py -> /var/tmp/portage/dev-python/neo4j-4.2.0/work/neo4j-4.2.0-python3_7/lib/neo4j
copying neo4j/exceptions.py -> /var/tmp/portage/dev-python/neo4j-4.2.0/work/neo4j-4.2.0-python3_7/lib/neo4j
copying neo4j/debug.py -> /var/tmp/portage/dev-python/neo4j-4.2.0/work/neo4j-4.2.0-python3_7/lib/neo4j
copying neo4j/data.py -> /var/tmp/portage/dev-python/neo4j-4.2.0/work/neo4j-4.2.0-python3_7/lib/neo4j
copying neo4j/conf.py -> /var/tmp/portage/dev-python/neo4j-4.2.0/work/neo4j-4.2.0-python3_7/lib/neo4j
copying neo4j/api.py -> /var/tmp/portage/dev-python/neo4j-4.2.0/work/neo4j-4.2.0-python3_7/lib/neo4j
copying neo4j/addressing.py -> /var/tmp/portage/dev-python/neo4j-4.2.0/work/neo4j-4.2.0-python3_7/lib/neo4j
copying neo4j/_exceptions.py -> /var/tmp/portage/dev-python/neo4j-4.2.0/work/neo4j-4.2.0-python3_7/lib/neo4j
copying neo4j/__init__.py -> /var/tmp/portage/dev-python/neo4j-4.2.0/work/neo4j-4.2.0-python3_7/lib/neo4j
creating /var/tmp/portage/dev-python/neo4j-4.2.0/work/neo4j-4.2.0-python3_7/lib/neo4j/work
copying neo4j/work/transaction.py -> /var/tmp/portage/dev-python/neo4j-4.2.0/work/neo4j-4.2.0-python3_7/lib/neo4j/work
copying neo4j/work/summary.py -> /var/tmp/portage/dev-python/neo4j-4.2.0/work/neo4j-4.2.0-python3_7/lib/neo4j/work
copying neo4j/work/simple.py -> /var/tmp/portage/dev-python/neo4j-4.2.0/work/neo4j-4.2.0-python3_7/lib/neo4j/work
copying neo4j/work/result.py -> /var/tmp/portage/dev-python/neo4j-4.2.0/work/neo4j-4.2.0-python3_7/lib/neo4j/work
copying neo4j/work/pipelining.py -> /var/tmp/portage/dev-python/neo4j-4.2.0/work/neo4j-4.2.0-python3_7/lib/neo4j/work
copying neo4j/work/__init__.py -> /var/tmp/portage/dev-python/neo4j-4.2.0/work/neo4j-4.2.0-python3_7/lib/neo4j/work
creating /var/tmp/portage/dev-python/neo4j-4.2.0/work/neo4j-4.2.0-python3_7/lib/neo4j/time
copying neo4j/time/metaclasses.py -> /var/tmp/portage/dev-python/neo4j-4.2.0/work/neo4j-4.2.0-python3_7/lib/neo4j/time
copying neo4j/time/hydration.py -> /var/tmp/portage/dev-python/neo4j-4.2.0/work/neo4j-4.2.0-python3_7/lib/neo4j/time
copying neo4j/time/clock_implementations.py -> /var/tmp/portage/dev-python/neo4j-4.2.0/work/neo4j-4.2.0-python3_7/lib/neo4j/time
copying neo4j/time/arithmetic.py -> /var/tmp/portage/dev-python/neo4j-4.2.0/work/neo4j-4.2.0-python3_7/lib/neo4j/time
copying neo4j/time/__main__.py -> /var/tmp/portage/dev-python/neo4j-4.2.0/work/neo4j-4.2.0-python3_7/lib/neo4j/time
copying neo4j/time/__init__.py -> /var/tmp/portage/dev-python/neo4j-4.2.0/work/neo4j-4.2.0-python3_7/lib/neo4j/time
creating /var/tmp/portage/dev-python/neo4j-4.2.0/work/neo4j-4.2.0-python3_7/lib/neo4j/spatial
copying neo4j/spatial/__init__.py -> /var/tmp/portage/dev-python/neo4j-4.2.0/work/neo4j-4.2.0-python3_7/lib/neo4j/spatial
creating /var/tmp/portage/dev-python/neo4j-4.2.0/work/neo4j-4.2.0-python3_7/lib/neo4j/io
copying neo4j/io/_common.py -> /var/tmp/portage/dev-python/neo4j-4.2.0/work/neo4j-4.2.0-python3_7/lib/neo4j/io
copying neo4j/io/_bolt4.py -> /var/tmp/portage/dev-python/neo4j-4.2.0/work/neo4j-4.2.0-python3_7/lib/neo4j/io
copying neo4j/io/_bolt3.py -> /var/tmp/portage/dev-python/neo4j-4.2.0/work/neo4j-4.2.0-python3_7/lib/neo4j/io
copying neo4j/io/__init__.py -> /var/tmp/portage/dev-python/neo4j-4.2.0/work/neo4j-4.2.0-python3_7/lib/neo4j/io
creating /var/tmp/portage/dev-python/neo4j-4.2.0/work/neo4j-4.2.0-python3_7/lib/neo4j/graph
copying neo4j/graph/__init__.py -> /var/tmp/portage/dev-python/neo4j-4.2.0/work/neo4j-4.2.0-python3_7/lib/neo4j/graph
warning: build_py: byte-compiling is disabled, skipping.

>>> Source compiled.
>>> Test phase [not enabled]: dev-python/neo4j-4.2.0

>>> Install dev-python/neo4j-4.2.0 into /var/tmp/portage/dev-python/neo4j-4.2.0/image
 * python3_7: running distutils-r1_run_phase distutils-r1_python_install
python3.7 setup.py install --skip-build --root=/var/tmp/portage/dev-python/neo4j-4.2.0/image/_python3.7
running install
running install_lib
creating /var/tmp/portage/dev-python/neo4j-4.2.0/image/_python3.7
creating /var/tmp/portage/dev-python/neo4j-4.2.0/image/_python3.7/usr
creating /var/tmp/portage/dev-python/neo4j-4.2.0/image/_python3.7/usr/lib
creating /var/tmp/portage/dev-python/neo4j-4.2.0/image/_python3.7/usr/lib/python3.7
creating /var/tmp/portage/dev-python/neo4j-4.2.0/image/_python3.7/usr/lib/python3.7/site-packages
creating /var/tmp/portage/dev-python/neo4j-4.2.0/image/_python3.7/usr/lib/python3.7/site-packages/neo4j
creating /var/tmp/portage/dev-python/neo4j-4.2.0/image/_python3.7/usr/lib/python3.7/site-packages/neo4j/graph
copying /var/tmp/portage/dev-python/neo4j-4.2.0/work/neo4j-4.2.0-python3_7/lib/neo4j/graph/__init__.py -> /var/tmp/portage/dev-python/neo4j-4.2.0/image/_python3.7/usr/lib/python3.7/site-packages/neo4j/graph
creating /var/tmp/portage/dev-python/neo4j-4.2.0/image/_python3.7/usr/lib/python3.7/site-packages/neo4j/io
copying /var/tmp/portage/dev-python/neo4j-4.2.0/work/neo4j-4.2.0-python3_7/lib/neo4j/io/__init__.py -> /var/tmp/portage/dev-python/neo4j-4.2.0/image/_python3.7/usr/lib/python3.7/site-packages/neo4j/io
copying /var/tmp/portage/dev-python/neo4j-4.2.0/work/neo4j-4.2.0-python3_7/lib/neo4j/io/_bolt3.py -> /var/tmp/portage/dev-python/neo4j-4.2.0/image/_python3.7/usr/lib/python3.7/site-packages/neo4j/io
copying /var/tmp/portage/dev-python/neo4j-4.2.0/work/neo4j-4.2.0-python3_7/lib/neo4j/io/_bolt4.py -> /var/tmp/portage/dev-python/neo4j-4.2.0/image/_python3.7/usr/lib/python3.7/site-packages/neo4j/io
copying /var/tmp/portage/dev-python/neo4j-4.2.0/work/neo4j-4.2.0-python3_7/lib/neo4j/io/_common.py -> /var/tmp/portage/dev-python/neo4j-4.2.0/image/_python3.7/usr/lib/python3.7/site-packages/neo4j/io
creating /var/tmp/portage/dev-python/neo4j-4.2.0/image/_python3.7/usr/lib/python3.7/site-packages/neo4j/spatial
copying /var/tmp/portage/dev-python/neo4j-4.2.0/work/neo4j-4.2.0-python3_7/lib/neo4j/spatial/__init__.py -> /var/tmp/portage/dev-python/neo4j-4.2.0/image/_python3.7/usr/lib/python3.7/site-packages/neo4j/spatial
creating /var/tmp/portage/dev-python/neo4j-4.2.0/image/_python3.7/usr/lib/python3.7/site-packages/neo4j/time
copying /var/tmp/portage/dev-python/neo4j-4.2.0/work/neo4j-4.2.0-python3_7/lib/neo4j/time/__init__.py -> /var/tmp/portage/dev-python/neo4j-4.2.0/image/_python3.7/usr/lib/python3.7/site-packages/neo4j/time
copying /var/tmp/portage/dev-python/neo4j-4.2.0/work/neo4j-4.2.0-python3_7/lib/neo4j/time/__main__.py -> /var/tmp/portage/dev-python/neo4j-4.2.0/image/_python3.7/usr/lib/python3.7/site-packages/neo4j/time
copying /var/tmp/portage/dev-python/neo4j-4.2.0/work/neo4j-4.2.0-python3_7/lib/neo4j/time/arithmetic.py -> /var/tmp/portage/dev-python/neo4j-4.2.0/image/_python3.7/usr/lib/python3.7/site-packages/neo4j/time
copying /var/tmp/portage/dev-python/neo4j-4.2.0/work/neo4j-4.2.0-python3_7/lib/neo4j/time/clock_implementations.py -> /var/tmp/portage/dev-python/neo4j-4.2.0/image/_python3.7/usr/lib/python3.7/site-packages/neo4j/time
copying /var/tmp/portage/dev-python/neo4j-4.2.0/work/neo4j-4.2.0-python3_7/lib/neo4j/time/hydration.py -> /var/tmp/portage/dev-python/neo4j-4.2.0/image/_python3.7/usr/lib/python3.7/site-packages/neo4j/time
copying /var/tmp/portage/dev-python/neo4j-4.2.0/work/neo4j-4.2.0-python3_7/lib/neo4j/time/metaclasses.py -> /var/tmp/portage/dev-python/neo4j-4.2.0/image/_python3.7/usr/lib/python3.7/site-packages/neo4j/time
creating /var/tmp/portage/dev-python/neo4j-4.2.0/image/_python3.7/usr/lib/python3.7/site-packages/neo4j/work
copying /var/tmp/portage/dev-python/neo4j-4.2.0/work/neo4j-4.2.0-python3_7/lib/neo4j/work/__init__.py -> /var/tmp/portage/dev-python/neo4j-4.2.0/image/_python3.7/usr/lib/python3.7/site-packages/neo4j/work
copying /var/tmp/portage/dev-python/neo4j-4.2.0/work/neo4j-4.2.0-python3_7/lib/neo4j/work/pipelining.py -> /var/tmp/portage/dev-python/neo4j-4.2.0/image/_python3.7/usr/lib/python3.7/site-packages/neo4j/work
copying /var/tmp/portage/dev-python/neo4j-4.2.0/work/neo4j-4.2.0-python3_7/lib/neo4j/work/result.py -> /var/tmp/portage/dev-python/neo4j-4.2.0/image/_python3.7/usr/lib/python3.7/site-packages/neo4j/work
copying /var/tmp/portage/dev-python/neo4j-4.2.0/work/neo4j-4.2.0-python3_7/lib/neo4j/work/simple.py -> /var/tmp/portage/dev-python/neo4j-4.2.0/image/_python3.7/usr/lib/python3.7/site-packages/neo4j/work
copying /var/tmp/portage/dev-python/neo4j-4.2.0/work/neo4j-4.2.0-python3_7/lib/neo4j/work/summary.py -> /var/tmp/portage/dev-python/neo4j-4.2.0/image/_python3.7/usr/lib/python3.7/site-packages/neo4j/work
copying /var/tmp/portage/dev-python/neo4j-4.2.0/work/neo4j-4.2.0-python3_7/lib/neo4j/work/transaction.py -> /var/tmp/portage/dev-python/neo4j-4.2.0/image/_python3.7/usr/lib/python3.7/site-packages/neo4j/work
copying /var/tmp/portage/dev-python/neo4j-4.2.0/work/neo4j-4.2.0-python3_7/lib/neo4j/__init__.py -> /var/tmp/portage/dev-python/neo4j-4.2.0/image/_python3.7/usr/lib/python3.7/site-packages/neo4j
copying /var/tmp/portage/dev-python/neo4j-4.2.0/work/neo4j-4.2.0-python3_7/lib/neo4j/_exceptions.py -> /var/tmp/portage/dev-python/neo4j-4.2.0/image/_python3.7/usr/lib/python3.7/site-packages/neo4j
copying /var/tmp/portage/dev-python/neo4j-4.2.0/work/neo4j-4.2.0-python3_7/lib/neo4j/addressing.py -> /var/tmp/portage/dev-python/neo4j-4.2.0/image/_python3.7/usr/lib/python3.7/site-packages/neo4j
copying /var/tmp/portage/dev-python/neo4j-4.2.0/work/neo4j-4.2.0-python3_7/lib/neo4j/api.py -> /var/tmp/portage/dev-python/neo4j-4.2.0/image/_python3.7/usr/lib/python3.7/site-packages/neo4j
copying /var/tmp/portage/dev-python/neo4j-4.2.0/work/neo4j-4.2.0-python3_7/lib/neo4j/conf.py -> /var/tmp/portage/dev-python/neo4j-4.2.0/image/_python3.7/usr/lib/python3.7/site-packages/neo4j
copying /var/tmp/portage/dev-python/neo4j-4.2.0/work/neo4j-4.2.0-python3_7/lib/neo4j/data.py -> /var/tmp/portage/dev-python/neo4j-4.2.0/image/_python3.7/usr/lib/python3.7/site-packages/neo4j
copying /var/tmp/portage/dev-python/neo4j-4.2.0/work/neo4j-4.2.0-python3_7/lib/neo4j/debug.py -> /var/tmp/portage/dev-python/neo4j-4.2.0/image/_python3.7/usr/lib/python3.7/site-packages/neo4j
copying /var/tmp/portage/dev-python/neo4j-4.2.0/work/neo4j-4.2.0-python3_7/lib/neo4j/exceptions.py -> /var/tmp/portage/dev-python/neo4j-4.2.0/image/_python3.7/usr/lib/python3.7/site-packages/neo4j
copying /var/tmp/portage/dev-python/neo4j-4.2.0/work/neo4j-4.2.0-python3_7/lib/neo4j/meta.py -> /var/tmp/portage/dev-python/neo4j-4.2.0/image/_python3.7/usr/lib/python3.7/site-packages/neo4j
copying /var/tmp/portage/dev-python/neo4j-4.2.0/work/neo4j-4.2.0-python3_7/lib/neo4j/packstream.py -> /var/tmp/portage/dev-python/neo4j-4.2.0/image/_python3.7/usr/lib/python3.7/site-packages/neo4j
copying /var/tmp/portage/dev-python/neo4j-4.2.0/work/neo4j-4.2.0-python3_7/lib/neo4j/routing.py -> /var/tmp/portage/dev-python/neo4j-4.2.0/image/_python3.7/usr/lib/python3.7/site-packages/neo4j
byte-compiling /var/tmp/portage/dev-python/neo4j-4.2.0/image/_python3.7/usr/lib/python3.7/site-packages/neo4j/graph/__init__.py to __init__.cpython-37.pyc
byte-compiling /var/tmp/portage/dev-python/neo4j-4.2.0/image/_python3.7/usr/lib/python3.7/site-packages/neo4j/io/__init__.py to __init__.cpython-37.pyc
byte-compiling /var/tmp/portage/dev-python/neo4j-4.2.0/image/_python3.7/usr/lib/python3.7/site-packages/neo4j/io/_bolt3.py to _bolt3.cpython-37.pyc
byte-compiling /var/tmp/portage/dev-python/neo4j-4.2.0/image/_python3.7/usr/lib/python3.7/site-packages/neo4j/io/_bolt4.py to _bolt4.cpython-37.pyc
byte-compiling /var/tmp/portage/dev-python/neo4j-4.2.0/image/_python3.7/usr/lib/python3.7/site-packages/neo4j/io/_common.py to _common.cpython-37.pyc
byte-compiling /var/tmp/portage/dev-python/neo4j-4.2.0/image/_python3.7/usr/lib/python3.7/site-packages/neo4j/spatial/__init__.py to __init__.cpython-37.pyc
byte-compiling /var/tmp/portage/dev-python/neo4j-4.2.0/image/_python3.7/usr/lib/python3.7/site-packages/neo4j/time/__init__.py to __init__.cpython-37.pyc
byte-compiling /var/tmp/portage/dev-python/neo4j-4.2.0/image/_python3.7/usr/lib/python3.7/site-packages/neo4j/time/__main__.py to __main__.cpython-37.pyc
byte-compiling /var/tmp/portage/dev-python/neo4j-4.2.0/image/_python3.7/usr/lib/python3.7/site-packages/neo4j/time/arithmetic.py to arithmetic.cpython-37.pyc
byte-compiling /var/tmp/portage/dev-python/neo4j-4.2.0/image/_python3.7/usr/lib/python3.7/site-packages/neo4j/time/clock_implementations.py to clock_implementations.cpython-37.pyc
byte-compiling /var/tmp/portage/dev-python/neo4j-4.2.0/image/_python3.7/usr/lib/python3.7/site-packages/neo4j/time/hydration.py to hydration.cpython-37.pyc
byte-compiling /var/tmp/portage/dev-python/neo4j-4.2.0/image/_python3.7/usr/lib/python3.7/site-packages/neo4j/time/metaclasses.py to metaclasses.cpython-37.pyc
byte-compiling /var/tmp/portage/dev-python/neo4j-4.2.0/image/_python3.7/usr/lib/python3.7/site-packages/neo4j/work/__init__.py to __init__.cpython-37.pyc
byte-compiling /var/tmp/portage/dev-python/neo4j-4.2.0/image/_python3.7/usr/lib/python3.7/site-packages/neo4j/work/pipelining.py to pipelining.cpython-37.pyc
byte-compiling /var/tmp/portage/dev-python/neo4j-4.2.0/image/_python3.7/usr/lib/python3.7/site-packages/neo4j/work/result.py to result.cpython-37.pyc
byte-compiling /var/tmp/portage/dev-python/neo4j-4.2.0/image/_python3.7/usr/lib/python3.7/site-packages/neo4j/work/simple.py to simple.cpython-37.pyc
byte-compiling /var/tmp/portage/dev-python/neo4j-4.2.0/image/_python3.7/usr/lib/python3.7/site-packages/neo4j/work/summary.py to summary.cpython-37.pyc
byte-compiling /var/tmp/portage/dev-python/neo4j-4.2.0/image/_python3.7/usr/lib/python3.7/site-packages/neo4j/work/transaction.py to transaction.cpython-37.pyc
byte-compiling /var/tmp/portage/dev-python/neo4j-4.2.0/image/_python3.7/usr/lib/python3.7/site-packages/neo4j/__init__.py to __init__.cpython-37.pyc
byte-compiling /var/tmp/portage/dev-python/neo4j-4.2.0/image/_python3.7/usr/lib/python3.7/site-packages/neo4j/_exceptions.py to _exceptions.cpython-37.pyc
byte-compiling /var/tmp/portage/dev-python/neo4j-4.2.0/image/_python3.7/usr/lib/python3.7/site-packages/neo4j/addressing.py to addressing.cpython-37.pyc
byte-compiling /var/tmp/portage/dev-python/neo4j-4.2.0/image/_python3.7/usr/lib/python3.7/site-packages/neo4j/api.py to api.cpython-37.pyc
byte-compiling /var/tmp/portage/dev-python/neo4j-4.2.0/image/_python3.7/usr/lib/python3.7/site-packages/neo4j/conf.py to conf.cpython-37.pyc
byte-compiling /var/tmp/portage/dev-python/neo4j-4.2.0/image/_python3.7/usr/lib/python3.7/site-packages/neo4j/data.py to data.cpython-37.pyc
byte-compiling /var/tmp/portage/dev-python/neo4j-4.2.0/image/_python3.7/usr/lib/python3.7/site-packages/neo4j/debug.py to debug.cpython-37.pyc
byte-compiling /var/tmp/portage/dev-python/neo4j-4.2.0/image/_python3.7/usr/lib/python3.7/site-packages/neo4j/exceptions.py to exceptions.cpython-37.pyc
byte-compiling /var/tmp/portage/dev-python/neo4j-4.2.0/image/_python3.7/usr/lib/python3.7/site-packages/neo4j/meta.py to meta.cpython-37.pyc
byte-compiling /var/tmp/portage/dev-python/neo4j-4.2.0/image/_python3.7/usr/lib/python3.7/site-packages/neo4j/packstream.py to packstream.cpython-37.pyc
byte-compiling /var/tmp/portage/dev-python/neo4j-4.2.0/image/_python3.7/usr/lib/python3.7/site-packages/neo4j/routing.py to routing.cpython-37.pyc
writing byte-compilation script '/var/tmp/portage/dev-python/neo4j-4.2.0/temp/tmp5jn77_x0.py'
/usr/bin/python3.7 /var/tmp/portage/dev-python/neo4j-4.2.0/temp/tmp5jn77_x0.py
removing /var/tmp/portage/dev-python/neo4j-4.2.0/temp/tmp5jn77_x0.py
writing byte-compilation script '/var/tmp/portage/dev-python/neo4j-4.2.0/temp/tmpq5uf1b58.py'
/usr/bin/python3.7 /var/tmp/portage/dev-python/neo4j-4.2.0/temp/tmpq5uf1b58.py
removing /var/tmp/portage/dev-python/neo4j-4.2.0/temp/tmpq5uf1b58.py
running install_egg_info
running egg_info
writing neo4j.egg-info/PKG-INFO
writing dependency_links to neo4j.egg-info/dependency_links.txt
writing entry points to neo4j.egg-info/entry_points.txt
writing requirements to neo4j.egg-info/requires.txt
writing top-level names to neo4j.egg-info/top_level.txt
reading manifest file 'neo4j.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
warning: no previously-included files matching '*.class' found anywhere in distribution
warning: no previously-included files matching '*.pyc' found anywhere in distribution
warning: no previously-included files matching '*.pyo' found anywhere in distribution
warning: no previously-included files matching '*.so' found anywhere in distribution
warning: no previously-included files matching '*.dll' found anywhere in distribution
warning: no previously-included files matching '__pycache__' found anywhere in distribution
no previously-included directories found matching 'tests'
writing manifest file 'neo4j.egg-info/SOURCES.txt'
Copying neo4j.egg-info to /var/tmp/portage/dev-python/neo4j-4.2.0/image/_python3.7/usr/lib/python3.7/site-packages/neo4j-4.2.0-py3.7.egg-info
running install_scripts
Installing pybolt script to /var/tmp/portage/dev-python/neo4j-4.2.0/image/_python3.7/usr/lib/python-exec/python3.7
 * Using python3.7 in global scope
 * python3_7: running distutils-r1_run_phase distutils-r1_python_install_all
>>> Completed installing dev-python/neo4j-4.2.0 into /var/tmp/portage/dev-python/neo4j-4.2.0/image

 * Final size of build directory: 1100 KiB (1.0 MiB)
 * Final size of installed tree:  1364 KiB (1.3 MiB)

 * Verifying compiled files in /usr/lib/python3.7/site-packages
```

**Comment by technige** [comment]
The error message is correct. There is indeed no module called `neo4j.bolt` in the official driver.

I'm not sure what you are attempting to run here exactly...
```
bash$ pybolt 
Traceback (most recent call last):
  File "/usr/lib/python-exec/python3.7/pybolt", line 33, in <module>
    sys.exit(load_entry_point('neo4j==4.2.0', 'console_scripts', 'pybolt')())
  File "/usr/lib/python3.7/site-packages/pkg_resources/__init__.py", line 473, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2843, in load_entry_point
    return ep.load()
  File "/usr/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2447, in load
    return self.resolve()
  File "/usr/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2453, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
ModuleNotFoundError: No module named 'neo4j.bolt'
```

... but there is no `pybolt` executable bundled with the driver either. This is not our code causing the error.

**Comment by technige** [comment]
The undocumented `pybolt` executable was removed in Neo4j 4.0. The corresponding entry point should have also been removed, but appears to have been left hanging. This will be bug fixed and removed.

For command line usage, please use the [Cypher Shell](https://neo4j.com/docs/operations-manual/current/tools/cypher-shell/) instead.
