### ISSUE TITLE
ProtocolError when connecting to Bolt interface

### ISSUE THREAD

**Issue by stevenpollack** [neo4j/neo4j-python-driver#58]
I'm on Mac OS X, and using the [neo4j 3.0 docker image](https://hub.docker.com/_/neo4j/):

```
docker run \
    --publish=7474:7474 --publish=7687:7687 \
    --volume=$HOME/neo4j/data:/data \
    neo4j:3.0
```

After installing the `neo4j` driver (`pip install neo4j-driver`), I tried taking bolt for a test spin:

``` python
from neo4j.v1 import GraphDatabase
GraphDatabase.driver("bolt://192.168.99.100:7687").session()
```

only to receive the `ProtocolError`:

```
Authentication token must contain: 'scheme : basic' (ID:F895AE27CA69CD94B808711EAA8C1F2B02B25613BD40C728D76C293EBCB2A00A)
```

The full Traceback is:

```
Traceback (most recent call last):
  File "/Users/user/anaconda/envs/gms/lib/python3.5/site-packages/neo4j/v1/session.py", line 146, in session
    session = self.session_pool.pop()
IndexError: pop from an empty deque

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/user/anaconda/envs/gms/lib/python3.5/site-packages/neo4j/v1/connection.py", line 384, in connect
    s = create_connection((host, port))
  File "/Users/user/anaconda/envs/gms/lib/python3.5/socket.py", line 711, in create_connection
    raise err
  File "/Users/user/anaconda/envs/gms/lib/python3.5/socket.py", line 702, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 61] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/user/anaconda/envs/gms/lib/python3.5/site-packages/neo4j/v1/session.py", line 148, in session
    session = Session(self)
  File "/Users/user/anaconda/envs/gms/lib/python3.5/site-packages/neo4j/v1/session.py", line 461, in __init__
    self.connection = connect(driver.host, driver.port, driver.ssl_context, **driver.config)
  File "/Users/user/anaconda/envs/gms/lib/python3.5/site-packages/neo4j/v1/connection.py", line 387, in connect
    raise ProtocolError("Unable to connect to %s on port %d - is the server running?" % (host, port))
neo4j.v1.exceptions.ProtocolError: Unable to connect to 192.168.99.100 on port 7473 - is the server running?
>>> GraphDatabase.driver("bolt://192.168.99.100:7687").session()
Traceback (most recent call last):
  File "/Users/user/anaconda/envs/gms/lib/python3.5/site-packages/neo4j/v1/session.py", line 146, in session
    session = self.session_pool.pop()
IndexError: pop from an empty deque

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/user/anaconda/envs/gms/lib/python3.5/site-packages/neo4j/v1/session.py", line 148, in session
    session = Session(self)
  File "/Users/user/anaconda/envs/gms/lib/python3.5/site-packages/neo4j/v1/session.py", line 461, in __init__
    self.connection = connect(driver.host, driver.port, driver.ssl_context, **driver.config)
  File "/Users/user/anaconda/envs/gms/lib/python3.5/site-packages/neo4j/v1/connection.py", line 446, in connect
    return Connection(s, der_encoded_server_certificate=der_encoded_server_certificate, **config)
  File "/Users/user/anaconda/envs/gms/lib/python3.5/site-packages/neo4j/v1/connection.py", line 235, in __init__
    self.fetch()
  File "/Users/user/anaconda/envs/gms/lib/python3.5/site-packages/neo4j/v1/connection.py", line 314, in fetch
    handler(*fields)
  File "/Users/user/anaconda/envs/gms/lib/python3.5/site-packages/neo4j/v1/connection.py", line 227, in on_failure
    raise ProtocolError(metadata.get("message", "Inititalisation failed"))
neo4j.v1.exceptions.ProtocolError: Authentication token must contain: 'scheme : basic' (ID:F895AE27CA69CD94B808711EAA8C1F2B02B25613BD40C728D76C293EBCB2A00A)
```

**Comment by stevenpollack** [comment]
Actually, after playing around and reading the tests, I realized that basic authentication was missing. The following works:

``` python
from neo4j.v1 import GraphDatabase, basic_auth
session = GraphDatabase.driver("bolt://192.168.99.100:7687", auth=basic_auth("neo4j", "neo4j")).session()
```

Furthermore:

``` python
>>> for record in session.run("UNWIND range(0,3) as r RETURN r"):
...     print(record["r"])
...
0
1
2
3
```

I will fork and update the README.
