### ISSUE TITLE
Protocol Error

### ISSUE THREAD

**Issue by Elektra58** [neo4j/neo4j-python-driver#63]
Strangely, I was able to use the driver for a while on one machine, then it failed. The same on all my other machines. I tried to run the very simple example you gave here on github.

``` python
Traceback (most recent call last):
  File "D:\Anaconda3\envs\py35\lib\site-packages\neo4j\v1\session.py", line 127, in session
    session = self.session_pool.pop()
IndexError: pop from an empty deque

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:/websites/neo_test/main.py", line 5, in <module>
    session = driver.session()
  File "D:\Anaconda3\envs\py35\lib\site-packages\neo4j\v1\session.py", line 129, in session
    session = Session(self)
  File "D:\Anaconda3\envs\py35\lib\site-packages\neo4j\v1\session.py", line 413, in __init__
    self.connection = connect(driver.host, driver.port, driver.ssl_context, **driver.config)
  File "D:\Anaconda3\envs\py35\lib\site-packages\neo4j\v1\connection.py", line 442, in connect
    return Connection(s, der_encoded_server_certificate=der_encoded_server_certificate, **config)
  File "D:\Anaconda3\envs\py35\lib\site-packages\neo4j\v1\connection.py", line 233, in __init__
    self.fetch()
  File "D:\Anaconda3\envs\py35\lib\site-packages\neo4j\v1\connection.py", line 312, in fetch
    handler(*fields)
  File "D:\Anaconda3\envs\py35\lib\site-packages\neo4j\v1\connection.py", line 225, in on_failure
    raise ProtocolError(metadata.get("message", "Inititalisation failed"))
neo4j.v1.exceptions.ProtocolError: Authentication token must contain: 'scheme : basic' (ID:938AD52F733B904F2FC8571C7A5B461627EE1D8AD9ED98D958DE98D091B355A9)

Process finished with exit code 1
```

Thank you for any hints.

**Comment by zhenlineo** [comment]
Your server had authentication turned on, which means you need to provide a auth token (e.g. neo4j, password) when you create the driver. See the examples in [manual](http://neo4j.com/docs/developer-manual/3.0/index.html#driver-manual-index)

We will update the example in readme to match default server settings too.

**Comment by Elektra58** [comment]
That did it. The example in the manual is more complete and also had the

``` python
result.close()
```

removed.

Thank you very much for your support!
