### ISSUE TITLE
StopAsyncIteration exception after second iteration when working with Async Driver

### ISSUE THREAD

**Issue by cuneyttyler** [neo4j/neo4j-python-driver#744]
Hi, 

Approximately 2 weeks ago I had entered an issue about async driver. I needed to close that GitHub account so the issue got removed. Here is the issue with exceptions ( Sorry for the delay):

First of all, when using async driver session with 'with' block this exception is thrown: `AttributeError: __enter__`

This is not blocking because without 'with' block, creating and closing sessions by ourselves we can workaround this.
Most importantly, when I use one driver (as suggested) for running parallel queries, second iteration afterwards, a `StopAsyncIteration` exception is thrown. Here is the stacktrace :

Traceback (most recent call last):
  File "/media/cnytync/42BECE42BECE2DEB/Dev/pyingest-fork/pyingest/src/main/ingest.py", line 385, in run_cql_wrapper
    await self.run_cql(session_index, cql, dict)
  File "/media/cnytync/42BECE42BECE2DEB/Dev/pyingest-fork/pyingest/src/main/ingest.py", line 404, in run_cql
    tx = await session.begin_transaction()
  File "/media/cnytync/42BECE42BECE2DEB/Dev/pyingest-fork/pyingest/venv/lib/python3.10/site-packages/neo4j/_async/work/session.py", line 303, in begin_transaction
    await self._open_transaction(
  File "/media/cnytync/42BECE42BECE2DEB/Dev/pyingest-fork/pyingest/venv/lib/python3.10/site-packages/neo4j/_async/work/session.py", line 257, in _open_transaction
    await self._connect(access_mode=access_mode)
  File "/media/cnytync/42BECE42BECE2DEB/Dev/pyingest-fork/pyingest/venv/lib/python3.10/site-packages/neo4j/_async/work/session.py", line 109, in _connect
    await super()._connect(access_mode)
  File "/media/cnytync/42BECE42BECE2DEB/Dev/pyingest-fork/pyingest/venv/lib/python3.10/site-packages/neo4j/_async/work/workspace.py", line 74, in _connect
    await self._pool.update_routing_table(
  File "/media/cnytync/42BECE42BECE2DEB/Dev/pyingest-fork/pyingest/venv/lib/python3.10/site-packages/neo4j/_async/io/_pool.py", line 560, in update_routing_table
    if await self._update_routing_table_from(
  File "/media/cnytync/42BECE42BECE2DEB/Dev/pyingest-fork/pyingest/venv/lib/python3.10/site-packages/neo4j/_async/io/_pool.py", line 495, in _update_routing_table_from
    new_routing_table = await self.fetch_routing_table(
  File "/media/cnytync/42BECE42BECE2DEB/Dev/pyingest-fork/pyingest/venv/lib/python3.10/site-packages/neo4j/_async/io/_pool.py", line 436, in fetch_routing_table
    new_routing_info = await self.fetch_routing_info(
  File "/media/cnytync/42BECE42BECE2DEB/Dev/pyingest-fork/pyingest/venv/lib/python3.10/site-packages/neo4j/_async/io/_pool.py", line 408, in fetch_routing_info
    routing_table = await cx.route(
  File "/media/cnytync/42BECE42BECE2DEB/Dev/pyingest-fork/pyingest/venv/lib/python3.10/site-packages/neo4j/_async/io/_bolt4.py", line 154, in route
    await self.fetch_all()
  File "/media/cnytync/42BECE42BECE2DEB/Dev/pyingest-fork/pyingest/venv/lib/python3.10/site-packages/neo4j/_async/io/_bolt.py", line 491, in fetch_all
    detail_delta, summary_delta = await self.fetch_message()
  File "/media/cnytync/42BECE42BECE2DEB/Dev/pyingest-fork/pyingest/venv/lib/python3.10/site-packages/neo4j/_async/io/_bolt4.py", line 283, in fetch_message
    await AsyncUtil.next(self.inbox)
  File "/media/cnytync/42BECE42BECE2DEB/Dev/pyingest-fork/pyingest/venv/lib/python3.10/site-packages/neo4j/_async_compat/util.py", line 32, in next
    return await it.__anext__()
  File "/media/cnytync/42BECE42BECE2DEB/Dev/pyingest-fork/pyingest/venv/lib/python3.10/site-packages/neo4j/_async/io/_common.py", line 81, in __anext__
    tag, fields = await self.pop()
  File "/media/cnytync/42BECE42BECE2DEB/Dev/pyingest-fork/pyingest/venv/lib/python3.10/site-packages/neo4j/_async/io/_common.py", line 75, in pop
    return await AsyncUtil.next(self._messages)
  File "/media/cnytync/42BECE42BECE2DEB/Dev/pyingest-fork/pyingest/venv/lib/python3.10/site-packages/neo4j/_async_compat/util.py", line 32, in next
    return await it.__anext__()
StopAsyncIteration

When I debug this, I see that driver awaits messages from Neo4j but couldn't receive, and consequently throws this exception.

So to workaround this I create new drivers for in each iteration but it's not suggested and I needed to edit driver's close method to close socket each time driver is closed so that no 'Too many files open' exception is thrown due to number of open sockets.

**Comment by cuneyttyler** [comment]
I resolved the issue. The reason for that is I created the tasks outside the asyncio event loop. My main function wasn't an async one, so that's related to StopAsyncIteration error. When I run my main function with asyncio.run, now it works.

**Comment by robsdedude** [comment]
Great to hear you found a solution for your issue. Regarding the `AttributeError: __enter__` that is because `AsyncSession`s are async context managers. So instead of `with async_driver.session() as session: ...` you should call `async with async_driver.session() as session: ...`. That will then call `async def __aenter__` on the `AsyncSession` object, which should exist.

Closing this issue as your issue is solved. If you have further questions, don't hesitate to ask.
