### ISSUE TITLE
Running as nobody (issue with `known_hosts` file not existing and not creatable)

### ISSUE THREAD

**Issue by serain** [neo4j/neo4j-python-driver#90]
I want to run some neo4j stuff from Celery tasks, within docker. Celery is running as `nobody`, for security reasons. `nobody` doesn't have a home directory and therefor I'm getting this issue:

```
celery_1 | [2016-09-13 13:22:00,096: INFO/Worker-1] ~~ [CONNECT] neo4j 7687
celery_1 | [2016-09-13 13:22:00,098: INFO/Worker-1] ~~ [SECURE] neo4j
celery_1 | [2016-09-13 13:22:00,208: ERROR/MainProcess] Task web.tasks.exec_module[b41dc7d4-7dff-4b7a-91d8-df199b674573] raised unexpected: FileNotFoundError(2, 'No such file or directory')
celery_1 | Traceback (most recent call last):
celery_1 |   File "/usr/local/lib/python3.5/site-packages/celery/app/trace.py", line 240, in trace_task
celery_1 |     R = retval = fun(*args, **kwargs)
celery_1 |   File "/usr/src/app/web/__init__.py", line 21, in __call__
celery_1 |     return TaskBase.__call__(self, *args, **kwargs)
celery_1 |   File "/usr/local/lib/python3.5/site-packages/celery/app/trace.py", line 438, in __protected_call__
celery_1 |     return self.run(*args, **kwargs)
celery_1 |   File "/usr/src/app/web/tasks.py", line 22, in exec_module
celery_1 |     module = importlib.import_module('%s.%s.%s' % (VISION_MODULES, module, module))
celery_1 |   File "/usr/local/lib/python3.5/importlib/__init__.py", line 126, in import_module
celery_1 |     return _bootstrap._gcd_import(name[level:], package, level)
celery_1 |   File "<frozen importlib._bootstrap>", line 986, in _gcd_import
celery_1 |   File "<frozen importlib._bootstrap>", line 969, in _find_and_load
celery_1 |   File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
celery_1 |   File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
celery_1 |   File "<frozen importlib._bootstrap_external>", line 665, in exec_module
celery_1 |   File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
celery_1 |   File "/usr/src/app/vision_modules/nmap_xml/nmap_xml.py", line 17, in <module>
celery_1 |     session = driver.session()
celery_1 |   File "/usr/local/lib/python3.5/site-packages/neo4j/v1/session.py", line 148, in session
celery_1 |     session = Session(self)
celery_1 |   File "/usr/local/lib/python3.5/site-packages/neo4j/v1/session.py", line 461, in __init__
celery_1 |     self.connection = connect(driver.host, driver.port, driver.ssl_context, **driver.config)
celery_1 |   File "/usr/local/lib/python3.5/site-packages/neo4j/v1/connection.py", line 427, in connect
celery_1 |     if not store.match_or_trust(host, der_encoded_server_certificate):
celery_1 |   File "/usr/local/lib/python3.5/site-packages/neo4j/v1/connection.py", line 380, in match_or_trust
celery_1 |     f_out = os_open(self.path, O_CREAT | O_APPEND | O_WRONLY, 0o600)  # TODO: Windows
celery_1 | FileNotFoundError: [Errno 2] No such file or directory: '/nonexistent/.neo4j/known_hosts'
```

Can we work without `known_hosts`? Can you suggest a work around when running as `nobody`?

**Comment by technige** [comment]
Use unencrypted connections for testing. In 1.1, the `ENCRYPTED_NON_LOCAL` default will make this easier.

**Comment by technige** [comment]
In 1.1 the `TRUST_ON_FIRST_USE` setting is deprecated and is therefore no longer default. Only this setting requires the `known_hosts` file so the correct approach (as of Dec 2016) will be to use unencrypted connections or `TRUST_ALL_CERTIFICATES`.
